// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CommandContrib {
    "id": string;
    "title": string;
    "keybind"?: string;
}

export interface CommandContribView {
    "pluginId": string;
    "id": string;
    "title": string;
    "keybind"?: string;
}

export interface Contributions {
    "renderers"?: RendererContrib[] | null;
    "urlSchemes"?: URLSchemeContrib[] | null;
    "panels"?: PanelContrib[] | null;
    "commands"?: CommandContrib[] | null;
    "themes"?: ThemeContrib[] | null;
    "settings"?: SettingsContrib[] | null;
    "devtools"?: DevToolsContrib[] | null;
}

export interface ContributionsView {
    "renderers": RendererContribView[] | null;
    "urlSchemes": URLSchemeContribView[] | null;
    "panels": PanelContribView[] | null;
    "commands": CommandContribView[] | null;
    "themes": ThemeContribView[] | null;
    "settings": SettingsContribView[] | null;
    "devtools": DevToolsContribView[] | null;
}

export interface DevToolsContrib {
    "id": string;
    "title": string;
    "entry": string;
}

export interface DevToolsContribView {
    "pluginId": string;
    "id": string;
    "title": string;
    "entry": string;
}

export interface InstalledPlugin {
    "manifest": Manifest;
    "dir": string;
    "enabled": boolean;
    "error"?: string;
}

export interface Manager {
}

export interface Manifest {
    "manifestVersion": number;
    "id": string;
    "name": string;
    "version": string;
    "description"?: string;
    "author"?: string;
    "license"?: string;
    "engines"?: { [_ in string]?: string } | null;
    "main"?: string;
    "backend"?: string;
    "permissions"?: string[] | null;
    "contributes"?: Contributions;
}

export interface PanelContrib {
    "id": string;
    "title": string;
    "icon"?: string;
    "entry": string;
    "location"?: string;
}

export interface PanelContribView {
    "pluginId": string;
    "id": string;
    "title": string;
    "icon"?: string;
    "entry": string;
    "location"?: string;
}

export interface RendererContrib {
    "id": string;
    "label": string;
    "extensions"?: string[] | null;
    "mime"?: string[] | null;
    "priority"?: number;
}

export interface RendererContribView {
    "pluginId": string;
    "id": string;
    "label": string;
    "extensions"?: string[] | null;
    "mime"?: string[] | null;
    "priority"?: number;
}

export interface SettingsContrib {
    "id": string;
    "title": string;
    "entry": string;
}

export interface SettingsContribView {
    "pluginId": string;
    "id": string;
    "title": string;
    "entry": string;
}

export interface ThemeContrib {
    "id": string;
    "label": string;
    "path": string;
}

export interface ThemeContribView {
    "pluginId": string;
    "id": string;
    "label": string;
    "path": string;
}

export interface URLSchemeContrib {
    "scheme": string;
    "handler"?: string;
}

export interface URLSchemeContribView {
    "pluginId": string;
    "scheme": string;
    "handler"?: string;
}
