// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandContrib {
    /**
     * Creates a new CommandContrib instance.
     * @param {Partial<CommandContrib>} [$$source = {}] - The source object to create the CommandContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keybind"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandContrib(/** @type {Partial<CommandContrib>} */($$parsedSource));
    }
}

export class CommandContribView {
    /**
     * Creates a new CommandContribView instance.
     * @param {Partial<CommandContribView>} [$$source = {}] - The source object to create the CommandContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keybind"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandContribView(/** @type {Partial<CommandContribView>} */($$parsedSource));
    }
}

export class Contributions {
    /**
     * Creates a new Contributions instance.
     * @param {Partial<Contributions>} [$$source = {}] - The source object to create the Contributions.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RendererContrib[] | undefined}
             */
            this["renderers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {URLSchemeContrib[] | undefined}
             */
            this["urlSchemes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PanelContrib[] | undefined}
             */
            this["panels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CommandContrib[] | undefined}
             */
            this["commands"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThemeContrib[] | undefined}
             */
            this["themes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SettingsContrib[] | undefined}
             */
            this["settings"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DevToolsContrib[] | undefined}
             */
            this["devtools"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Contributions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Contributions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("renderers" in $$parsedSource) {
            $$parsedSource["renderers"] = $$createField0_0($$parsedSource["renderers"]);
        }
        if ("urlSchemes" in $$parsedSource) {
            $$parsedSource["urlSchemes"] = $$createField1_0($$parsedSource["urlSchemes"]);
        }
        if ("panels" in $$parsedSource) {
            $$parsedSource["panels"] = $$createField2_0($$parsedSource["panels"]);
        }
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField4_0($$parsedSource["themes"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        if ("devtools" in $$parsedSource) {
            $$parsedSource["devtools"] = $$createField6_0($$parsedSource["devtools"]);
        }
        return new Contributions(/** @type {Partial<Contributions>} */($$parsedSource));
    }
}

export class ContributionsView {
    /**
     * Creates a new ContributionsView instance.
     * @param {Partial<ContributionsView>} [$$source = {}] - The source object to create the ContributionsView.
     */
    constructor($$source = {}) {
        if (!("renderers" in $$source)) {
            /**
             * @member
             * @type {RendererContribView[]}
             */
            this["renderers"] = [];
        }
        if (!("urlSchemes" in $$source)) {
            /**
             * @member
             * @type {URLSchemeContribView[]}
             */
            this["urlSchemes"] = [];
        }
        if (!("panels" in $$source)) {
            /**
             * @member
             * @type {PanelContribView[]}
             */
            this["panels"] = [];
        }
        if (!("commands" in $$source)) {
            /**
             * @member
             * @type {CommandContribView[]}
             */
            this["commands"] = [];
        }
        if (!("themes" in $$source)) {
            /**
             * @member
             * @type {ThemeContribView[]}
             */
            this["themes"] = [];
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {SettingsContribView[]}
             */
            this["settings"] = [];
        }
        if (!("devtools" in $$source)) {
            /**
             * @member
             * @type {DevToolsContribView[]}
             */
            this["devtools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContributionsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContributionsView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType19;
        const $$createField3_0 = $$createType21;
        const $$createField4_0 = $$createType23;
        const $$createField5_0 = $$createType25;
        const $$createField6_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("renderers" in $$parsedSource) {
            $$parsedSource["renderers"] = $$createField0_0($$parsedSource["renderers"]);
        }
        if ("urlSchemes" in $$parsedSource) {
            $$parsedSource["urlSchemes"] = $$createField1_0($$parsedSource["urlSchemes"]);
        }
        if ("panels" in $$parsedSource) {
            $$parsedSource["panels"] = $$createField2_0($$parsedSource["panels"]);
        }
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField4_0($$parsedSource["themes"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        if ("devtools" in $$parsedSource) {
            $$parsedSource["devtools"] = $$createField6_0($$parsedSource["devtools"]);
        }
        return new ContributionsView(/** @type {Partial<ContributionsView>} */($$parsedSource));
    }
}

export class DevToolsContrib {
    /**
     * Creates a new DevToolsContrib instance.
     * @param {Partial<DevToolsContrib>} [$$source = {}] - The source object to create the DevToolsContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevToolsContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DevToolsContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevToolsContrib(/** @type {Partial<DevToolsContrib>} */($$parsedSource));
    }
}

export class DevToolsContribView {
    /**
     * Creates a new DevToolsContribView instance.
     * @param {Partial<DevToolsContribView>} [$$source = {}] - The source object to create the DevToolsContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevToolsContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DevToolsContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevToolsContribView(/** @type {Partial<DevToolsContribView>} */($$parsedSource));
    }
}

export class InstalledPlugin {
    /**
     * Creates a new InstalledPlugin instance.
     * @param {Partial<InstalledPlugin>} [$$source = {}] - The source object to create the InstalledPlugin.
     */
    constructor($$source = {}) {
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {Manifest}
             */
            this["manifest"] = (new Manifest());
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledPlugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledPlugin}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        return new InstalledPlugin(/** @type {Partial<InstalledPlugin>} */($$parsedSource));
    }
}

export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}

export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("manifestVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["manifestVersion"] = 0;
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["engines"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["main"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Contributions | undefined}
             */
            this["contributes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType29;
        const $$createField10_0 = $$createType30;
        const $$createField11_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("engines" in $$parsedSource) {
            $$parsedSource["engines"] = $$createField7_0($$parsedSource["engines"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField10_0($$parsedSource["permissions"]);
        }
        if ("contributes" in $$parsedSource) {
            $$parsedSource["contributes"] = $$createField11_0($$parsedSource["contributes"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

export class PanelContrib {
    /**
     * Creates a new PanelContrib instance.
     * @param {Partial<PanelContrib>} [$$source = {}] - The source object to create the PanelContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["location"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PanelContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelContrib(/** @type {Partial<PanelContrib>} */($$parsedSource));
    }
}

export class PanelContribView {
    /**
     * Creates a new PanelContribView instance.
     * @param {Partial<PanelContribView>} [$$source = {}] - The source object to create the PanelContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["location"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PanelContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelContribView(/** @type {Partial<PanelContribView>} */($$parsedSource));
    }
}

export class RendererContrib {
    /**
     * Creates a new RendererContrib instance.
     * @param {Partial<RendererContrib>} [$$source = {}] - The source object to create the RendererContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["extensions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["mime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["priority"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RendererContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RendererContrib}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType30;
        const $$createField3_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        if ("mime" in $$parsedSource) {
            $$parsedSource["mime"] = $$createField3_0($$parsedSource["mime"]);
        }
        return new RendererContrib(/** @type {Partial<RendererContrib>} */($$parsedSource));
    }
}

export class RendererContribView {
    /**
     * Creates a new RendererContribView instance.
     * @param {Partial<RendererContribView>} [$$source = {}] - The source object to create the RendererContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["extensions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["mime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["priority"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RendererContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RendererContribView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType30;
        const $$createField4_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        if ("mime" in $$parsedSource) {
            $$parsedSource["mime"] = $$createField4_0($$parsedSource["mime"]);
        }
        return new RendererContribView(/** @type {Partial<RendererContribView>} */($$parsedSource));
    }
}

export class SettingsContrib {
    /**
     * Creates a new SettingsContrib instance.
     * @param {Partial<SettingsContrib>} [$$source = {}] - The source object to create the SettingsContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsContrib(/** @type {Partial<SettingsContrib>} */($$parsedSource));
    }
}

export class SettingsContribView {
    /**
     * Creates a new SettingsContribView instance.
     * @param {Partial<SettingsContribView>} [$$source = {}] - The source object to create the SettingsContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entry"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsContribView(/** @type {Partial<SettingsContribView>} */($$parsedSource));
    }
}

export class ThemeContrib {
    /**
     * Creates a new ThemeContrib instance.
     * @param {Partial<ThemeContrib>} [$$source = {}] - The source object to create the ThemeContrib.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeContrib(/** @type {Partial<ThemeContrib>} */($$parsedSource));
    }
}

export class ThemeContribView {
    /**
     * Creates a new ThemeContribView instance.
     * @param {Partial<ThemeContribView>} [$$source = {}] - The source object to create the ThemeContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeContribView(/** @type {Partial<ThemeContribView>} */($$parsedSource));
    }
}

export class URLSchemeContrib {
    /**
     * Creates a new URLSchemeContrib instance.
     * @param {Partial<URLSchemeContrib>} [$$source = {}] - The source object to create the URLSchemeContrib.
     */
    constructor($$source = {}) {
        if (!("scheme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scheme"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["handler"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLSchemeContrib instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {URLSchemeContrib}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLSchemeContrib(/** @type {Partial<URLSchemeContrib>} */($$parsedSource));
    }
}

export class URLSchemeContribView {
    /**
     * Creates a new URLSchemeContribView instance.
     * @param {Partial<URLSchemeContribView>} [$$source = {}] - The source object to create the URLSchemeContribView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("scheme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scheme"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["handler"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLSchemeContribView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {URLSchemeContribView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLSchemeContribView(/** @type {Partial<URLSchemeContribView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RendererContrib.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = URLSchemeContrib.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PanelContrib.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = CommandContrib.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ThemeContrib.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SettingsContrib.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = DevToolsContrib.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = RendererContribView.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = URLSchemeContribView.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = PanelContribView.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = CommandContribView.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ThemeContribView.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = SettingsContribView.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = DevToolsContribView.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = Manifest.createFrom;
const $$createType29 = $Create.Map($Create.Any, $Create.Any);
const $$createType30 = $Create.Array($Create.Any);
const $$createType31 = Contributions.createFrom;
