packages:
  - frontend

pnpm:
  minimumReleaseAge: 1440
  trustPolicy: no-downgrade
  trustPolicyIgnoreAfter: 525600
  blockExoticSubdeps: true
  strictDepBuilds: false
  engineStrict: true
  autoInstallPeers: true
  pmOnFail: error
  allowBuilds:
    esbuild: true
