// Code generated by build/scripts/gen-brand.mjs. DO NOT EDIT.

package brand

import (
	"strconv"

	"renbrowser/internal/paths"
)

const (
	Company            = "Quad4"
	DisplayName        = "Ren Browser"
	Slug               = "renbrowser"
	BundleID           = "io.quad4.renbrowser"
	Description        = "Reticulum browser for NomadNet pages"
	Tagline            = "Reticulum browser for NomadNet pages."
	Comments           = "Micron-first mesh browser for NomadNet"
	Copyright          = "(c) 2026 Quad4"
	Version            = "0.2.0"
	Homepage           = "https://quad4.io"
	DataDirName        = ".renbrowser"
	DBFileName         = "renbrowser.db"
	EnvPrefix          = "REN_BROWSER"
	LocalStoragePrefix = "renbrowser"
	IndexedDBName      = "renbrowser_micron_wasm_parsers"
	ProxyHeader        = "X-RenBrowser-Base-Path"
	TempFilePrefix     = "renbrowser-rns-"
	WailsVersion       = "v3.0.0-alpha2"
	WasmExecDomID      = "renbrowser-micron-wasm-exec"
	WasmGlobalFlag     = "__renbrowserMicronWasmWrapped"
)

func DataDir() string {
	return DataDirName
}

func DBFile() string {
	return DBFileName
}

func DefaultDBPath() string {
	return paths.Join(DataDirName, DBFileName)
}

func ProfilesDir() string {
	return paths.Join(DataDirName, "profiles")
}

func ProfileDBPath(name string) string {
	if name == "" || name == "default" {
		return DefaultDBPath()
	}
	return paths.Join(DataDirName, "profiles", name, DBFileName)
}

func LegacyStatePath() string {
	return paths.Join(DataDirName, "state.json")
}

func LocalStorageKey(safe string, dataVersion int) string {
	return LocalStoragePrefix + ":" + safe + ":v" + strconv.Itoa(dataVersion)
}
