// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as micron$0 from "../micron/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nomadnet$0 from "../nomadnet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rns$0 from "../rns/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddFavorite(url: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1018688458, url);
}

export function AttachStack(stack: rns$0.Stack | null): $CancellablePromise<void> {
    return $Call.ByID(1182225214, stack);
}

/**
 * CancelDownload aborts an in-flight download started via DownloadToDir.
 * Returns false if the download is unknown or already finished.
 */
export function CancelDownload(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2459978457, id);
}

export function CaptureWindowState(): $CancellablePromise<$models.WindowState> {
    return $Call.ByID(2070387988);
}

export function ClearBrowsingHistory(): $CancellablePromise<void> {
    return $Call.ByID(3405602571);
}

export function ClearDevLogs(): $CancellablePromise<void> {
    return $Call.ByID(1245444528);
}

export function ClearPageCache(): $CancellablePromise<number> {
    return $Call.ByID(3956852603);
}

export function ConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1926139322);
}

/**
 * DismissDownload removes a finished or failed download entry from the
 * active downloads list without affecting any file already written to disk.
 */
export function DismissDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2093548437, id);
}

export function DownloadFile(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(2486412905, rawURL);
}

export function DownloadToDir(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(1534417513, rawURL);
}

export function ExportDevLogs(): $CancellablePromise<string> {
    return $Call.ByID(3106065651);
}

export function ExportProfile(): $CancellablePromise<string> {
    return $Call.ByID(3287960970);
}

export function ExportTheme(): $CancellablePromise<string> {
    return $Call.ByID(2779828062);
}

export function FetchCommunityInterfaces(): $CancellablePromise<$models.CommunityFetchResult> {
    return $Call.ByID(44455642);
}

export function FetchMicronParserGoRelease(tag: string): $CancellablePromise<$models.MicronWasmFetchResult> {
    return $Call.ByID(1537521279, tag);
}

export function GetAboutInfo(): $CancellablePromise<$models.AboutInfo> {
    return $Call.ByID(1103929366);
}

export function GetBrowserPrefs(): $CancellablePromise<$models.BrowserPrefs> {
    return $Call.ByID(3733174083);
}

export function GetBrowsingHistory(limit: number): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(1328109872, limit);
}

export function GetDevLogs(): $CancellablePromise<$models.DevLogEntry[] | null> {
    return $Call.ByID(901461935);
}

export function GetDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(2239155440);
}

export function GetFavorites(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2054671026);
}

export function GetKeybinds(): $CancellablePromise<$models.KeybindSettings> {
    return $Call.ByID(2624266744);
}

export function GetLastPage(): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(1927485938);
}

export function GetNetworkLog(): $CancellablePromise<$models.NetworkEntry[] | null> {
    return $Call.ByID(560803913);
}

export function GetPageCacheStats(): $CancellablePromise<$models.PageCacheStats> {
    return $Call.ByID(1429924087);
}

export function GetRecent(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2288988822);
}

export function GetReticulumConfigText(): $CancellablePromise<string> {
    return $Call.ByID(98426270);
}

export function GetRuntimeConfig(): $CancellablePromise<$models.RuntimeConfig> {
    return $Call.ByID(1108835153);
}

export function GetStatus(): $CancellablePromise<rns$0.Status> {
    return $Call.ByID(3416137943);
}

export function GetStoreHealth(): $CancellablePromise<$models.StoreHealth> {
    return $Call.ByID(4060167012);
}

export function GetTabs(): $CancellablePromise<$models.TabSnapshot[] | null> {
    return $Call.ByID(2561211797);
}

export function GetTheme(): $CancellablePromise<$models.ThemeSettings> {
    return $Call.ByID(1060168362);
}

export function GetWindowChrome(): $CancellablePromise<$models.WindowChrome> {
    return $Call.ByID(4083006883);
}

export function GetWindowState(): $CancellablePromise<$models.WindowState> {
    return $Call.ByID(2477522246);
}

export function GoBack(): $CancellablePromise<string> {
    return $Call.ByID(4055004086);
}

export function GoForward(): $CancellablePromise<string> {
    return $Call.ByID(2359808390);
}

export function HistoryState(): $CancellablePromise<$models.HistoryState> {
    return $Call.ByID(1224281278);
}

export function IdentifyToNode(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(2577137458, rawURL);
}

export function ImportCommunityInterfaces(configs: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(473619687, configs);
}

export function ImportProfile(jsonData: string): $CancellablePromise<void> {
    return $Call.ByID(1524005335, jsonData);
}

export function ImportTheme(jsonData: string): $CancellablePromise<$models.ThemeSettings> {
    return $Call.ByID(187729019, jsonData);
}

export function InitialWindowOptions(frameless: boolean, reset: boolean): $CancellablePromise<application$0.WebviewWindowOptions> {
    return $Call.ByID(1225990025, frameless, reset);
}

/**
 * ListActiveDownloads returns the current set of in-flight and recently
 * finished mesh file downloads for the downloads panel.
 */
export function ListActiveDownloads(): $CancellablePromise<$models.ActiveDownload[] | null> {
    return $Call.ByID(3518671294);
}

export function ListDownloads(): $CancellablePromise<$models.DownloadItem[] | null> {
    return $Call.ByID(457843428);
}

export function ListInterfaces(): $CancellablePromise<rns$0.InterfaceInfo[] | null> {
    return $Call.ByID(533776795);
}

export function ListNodes(): $CancellablePromise<nomadnet$0.Node[] | null> {
    return $Call.ByID(264558488);
}

export function ListProfiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2153055525);
}

export function ListSystemFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2011568752);
}

export function Navigate(rawURL: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(1556317992, rawURL);
}

export function NavigateFresh(rawURL: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(2415389260, rawURL);
}

export function OpenDownloadPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1130095724, path);
}

export function OpenFreshURL(rawURL: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(2298746954, rawURL);
}

export function OpenNewWindow(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(765039791, rawURL);
}

export function OpenURL(rawURL: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(625938856, rawURL);
}

export function PickDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(3989255669);
}

export function PickPluginDir(): $CancellablePromise<string> {
    return $Call.ByID(1804809056);
}

export function PickPluginZip(): $CancellablePromise<string> {
    return $Call.ByID(972349000);
}

export function PluginManager(): $CancellablePromise<plugins$0.Manager | null> {
    return $Call.ByID(1606493335);
}

export function ProfileName(): $CancellablePromise<string> {
    return $Call.ByID(1189992039);
}

export function ProfilePath(): $CancellablePromise<string> {
    return $Call.ByID(1012136267);
}

export function ReloadReticulumConfig(): $CancellablePromise<string> {
    return $Call.ByID(1449773992);
}

export function RemoveFavorite(url: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1692284655, url);
}

export function RenderRaw(path: string, raw: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(52499783, path, raw);
}

export function RenderRawBase64(path: string, rawB64: string): $CancellablePromise<$models.PageResponse> {
    return $Call.ByID(1458605216, path, rawB64);
}

export function ResetDatabase(): $CancellablePromise<void> {
    return $Call.ByID(2200853935);
}

export function ResetSettings(): $CancellablePromise<$models.SettingsReset> {
    return $Call.ByID(532680647);
}

export function ResetWindowState(): $CancellablePromise<$models.WindowState> {
    return $Call.ByID(2002111347);
}

export function ResolveMicronLink(currentURL: string, destination: string, fieldsSpec: string, inputs: micron$0.FieldInput[] | null): $CancellablePromise<string> {
    return $Call.ByID(1146851467, currentURL, destination, fieldsSpec, inputs);
}

export function SaveDownload(rawURL: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(2853347910, rawURL, destPath);
}

export function SaveReticulumConfigText(text: string): $CancellablePromise<void> {
    return $Call.ByID(20987523, text);
}

export function SaveTabs(tabs: $models.TabSnapshot[] | null): $CancellablePromise<$models.TabSnapshot[] | null> {
    return $Call.ByID(3064793674, tabs);
}

export function SaveTextToDownloadDir(filename: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(4096126827, filename, content);
}

export function SaveWindowState(state: $models.WindowState): $CancellablePromise<$models.WindowState> {
    return $Call.ByID(3316457255, state);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1090166880, app);
}

export function SetBrowserPrefs(prefs: $models.BrowserPrefs): $CancellablePromise<$models.BrowserPrefs> {
    return $Call.ByID(1918193151, prefs);
}

export function SetDownloadDir(dir: string): $CancellablePromise<string> {
    return $Call.ByID(2475053084, dir);
}

export function SetInterfaceEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1901047613, name, enabled);
}

export function SetKeybinds(settings: $models.KeybindSettings): $CancellablePromise<$models.KeybindSettings> {
    return $Call.ByID(1520408612, settings);
}

export function SetLogLevel(level: number): $CancellablePromise<number> {
    return $Call.ByID(204071525, level);
}

export function SetNativeTitlebar(enabled: boolean): $CancellablePromise<$models.BrowserPrefs> {
    return $Call.ByID(1710067077, enabled);
}

export function SetPluginManager(manager: plugins$0.Manager | null): $CancellablePromise<void> {
    return $Call.ByID(3077852421, manager);
}

export function SetTheme(theme: $models.ThemeSettings): $CancellablePromise<$models.ThemeSettings> {
    return $Call.ByID(1442035638, theme);
}

export function ShowDownloadDir(): $CancellablePromise<void> {
    return $Call.ByID(1423237973);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1497311545);
}

export function StartReticulum(): $CancellablePromise<void> {
    return $Call.ByID(905786083);
}

export function StopReticulum(): $CancellablePromise<void> {
    return $Call.ByID(3051993617);
}

export function Store(): $CancellablePromise<store$0.Store | null> {
    return $Call.ByID(3681528604);
}

export function SyncMobileChrome(chromeBg: string, lightStatusIcons: boolean): $CancellablePromise<void> {
    return $Call.ByID(345790524, chromeBg, lightStatusIcons);
}

export function ToggleFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(607083998);
}
