// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as micron$0 from "../micron/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nomadnet$0 from "../nomadnet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rns$0 from "../rns/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} url
 * @returns {$CancellablePromise<string[]>}
 */
export function AddFavorite(url) {
    return $Call.ByID(1018688458, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {rns$0.Stack | null} stack
 * @returns {$CancellablePromise<void>}
 */
export function AttachStack(stack) {
    return $Call.ByID(1182225214, stack);
}

/**
 * @param {application$0.Window} window
 * @returns {$CancellablePromise<void>}
 */
export function AttachWindowPersistence(window) {
    return $Call.ByID(3944025841, window);
}

/**
 * @returns {$CancellablePromise<$models.WindowState>}
 */
export function CaptureWindowState() {
    return $Call.ByID(2070387988).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearDevLogs() {
    return $Call.ByID(1245444528);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function ClearPageCache() {
    return $Call.ByID(3956852603);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ConfigPath() {
    return $Call.ByID(1926139322);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFile(rawURL) {
    return $Call.ByID(2486412905, rawURL);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<string>}
 */
export function DownloadToDir(rawURL) {
    return $Call.ByID(1534417513, rawURL);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportDevLogs() {
    return $Call.ByID(3106065651);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportProfile() {
    return $Call.ByID(3287960970);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportTheme() {
    return $Call.ByID(2779828062);
}

/**
 * @returns {$CancellablePromise<rns$0.CommunityInterface[]>}
 */
export function FetchCommunityInterfaces() {
    return $Call.ByID(44455642).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} tag
 * @returns {$CancellablePromise<$models.MicronWasmFetchResult>}
 */
export function FetchMicronParserGoRelease(tag) {
    return $Call.ByID(1537521279, tag).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AboutInfo>}
 */
export function GetAboutInfo() {
    return $Call.ByID(1103929366).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.BrowserPrefs>}
 */
export function GetBrowserPrefs() {
    return $Call.ByID(3733174083).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetBrowsingHistory(limit) {
    return $Call.ByID(1328109872, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DevLogEntry[]>}
 */
export function GetDevLogs() {
    return $Call.ByID(901461935).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadDir() {
    return $Call.ByID(2239155440);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFavorites() {
    return $Call.ByID(2054671026).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.KeybindSettings>}
 */
export function GetKeybinds() {
    return $Call.ByID(2624266744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function GetLastPage() {
    return $Call.ByID(1927485938).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.NetworkEntry[]>}
 */
export function GetNetworkLog() {
    return $Call.ByID(560803913).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PageCacheStats>}
 */
export function GetPageCacheStats() {
    return $Call.ByID(1429924087).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetRecent() {
    return $Call.ByID(2288988822).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetReticulumConfigText() {
    return $Call.ByID(98426270);
}

/**
 * @returns {$CancellablePromise<$models.RuntimeConfig>}
 */
export function GetRuntimeConfig() {
    return $Call.ByID(1108835153).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<rns$0.Status>}
 */
export function GetStatus() {
    return $Call.ByID(3416137943).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StoreHealth>}
 */
export function GetStoreHealth() {
    return $Call.ByID(4060167012).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TabSnapshot[]>}
 */
export function GetTabs() {
    return $Call.ByID(2561211797).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ThemeSettings>}
 */
export function GetTheme() {
    return $Call.ByID(1060168362).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WindowChrome>}
 */
export function GetWindowChrome() {
    return $Call.ByID(4083006883).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WindowState>}
 */
export function GetWindowState() {
    return $Call.ByID(2477522246).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GoBack() {
    return $Call.ByID(4055004086);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GoForward() {
    return $Call.ByID(2359808390);
}

/**
 * @returns {$CancellablePromise<$models.HistoryState>}
 */
export function HistoryState() {
    return $Call.ByID(1224281278).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function IdentifyToNode(rawURL) {
    return $Call.ByID(2577137458, rawURL);
}

/**
 * @param {string} jsonData
 * @returns {$CancellablePromise<void>}
 */
export function ImportProfile(jsonData) {
    return $Call.ByID(1524005335, jsonData);
}

/**
 * @param {string} jsonData
 * @returns {$CancellablePromise<$models.ThemeSettings>}
 */
export function ImportTheme(jsonData) {
    return $Call.ByID(187729019, jsonData).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {boolean} frameless
 * @param {boolean} reset
 * @returns {$CancellablePromise<application$0.WebviewWindowOptions>}
 */
export function InitialWindowOptions(frameless, reset) {
    return $Call.ByID(1225990025, frameless, reset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DownloadItem[]>}
 */
export function ListDownloads() {
    return $Call.ByID(457843428).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<rns$0.InterfaceInfo[]>}
 */
export function ListInterfaces() {
    return $Call.ByID(533776795).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @returns {$CancellablePromise<nomadnet$0.Node[]>}
 */
export function ListNodes() {
    return $Call.ByID(264558488).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListProfiles() {
    return $Call.ByID(2153055525).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSystemFonts() {
    return $Call.ByID(2011568752).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function Navigate(rawURL) {
    return $Call.ByID(1556317992, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function NavigateFresh(rawURL) {
    return $Call.ByID(2415389260, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenDownloadPath(path) {
    return $Call.ByID(1130095724, path);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function OpenFreshURL(rawURL) {
    return $Call.ByID(2298746954, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenNewWindow(rawURL) {
    return $Call.ByID(765039791, rawURL);
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function OpenURL(rawURL) {
    return $Call.ByID(625938856, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickDownloadDir() {
    return $Call.ByID(3989255669);
}

/**
 * @returns {$CancellablePromise<plugins$0.Manager | null>}
 */
export function PluginManager() {
    return $Call.ByID(1606493335).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ProfileName() {
    return $Call.ByID(1189992039);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ProfilePath() {
    return $Call.ByID(1012136267);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReloadReticulumConfig() {
    return $Call.ByID(1449773992);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<string[]>}
 */
export function RemoveFavorite(url) {
    return $Call.ByID(1692284655, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} path
 * @param {string} raw
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function RenderRaw(path, raw) {
    return $Call.ByID(52499783, path, raw).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} path
 * @param {string} rawB64
 * @returns {$CancellablePromise<$models.PageResponse>}
 */
export function RenderRawBase64(path, rawB64) {
    return $Call.ByID(1458605216, path, rawB64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetDatabase() {
    return $Call.ByID(2200853935);
}

/**
 * @returns {$CancellablePromise<$models.SettingsReset>}
 */
export function ResetSettings() {
    return $Call.ByID(532680647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WindowState>}
 */
export function ResetWindowState() {
    return $Call.ByID(2002111347).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} currentURL
 * @param {string} destination
 * @param {string} fieldsSpec
 * @param {micron$0.FieldInput[]} inputs
 * @returns {$CancellablePromise<string>}
 */
export function ResolveMicronLink(currentURL, destination, fieldsSpec, inputs) {
    return $Call.ByID(1146851467, currentURL, destination, fieldsSpec, inputs);
}

/**
 * @param {string} rawURL
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function SaveDownload(rawURL, destPath) {
    return $Call.ByID(2853347910, rawURL, destPath);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SaveReticulumConfigText(text) {
    return $Call.ByID(20987523, text);
}

/**
 * @param {$models.TabSnapshot[]} tabs
 * @returns {$CancellablePromise<$models.TabSnapshot[]>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(3064793674, tabs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} filename
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveTextToDownloadDir(filename, content) {
    return $Call.ByID(4096126827, filename, content);
}

/**
 * @param {$models.WindowState} state
 * @returns {$CancellablePromise<$models.WindowState>}
 */
export function SaveWindowState(state) {
    return $Call.ByID(3316457255, state).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1090166880, app);
}

/**
 * @param {$models.BrowserPrefs} prefs
 * @returns {$CancellablePromise<$models.BrowserPrefs>}
 */
export function SetBrowserPrefs(prefs) {
    return $Call.ByID(1918193151, prefs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function SetDownloadDir(dir) {
    return $Call.ByID(2475053084, dir);
}

/**
 * @param {string} name
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetInterfaceEnabled(name, enabled) {
    return $Call.ByID(1901047613, name, enabled);
}

/**
 * @param {$models.KeybindSettings} settings
 * @returns {$CancellablePromise<$models.KeybindSettings>}
 */
export function SetKeybinds(settings) {
    return $Call.ByID(1520408612, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {number} level
 * @returns {$CancellablePromise<number>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(204071525, level);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.BrowserPrefs>}
 */
export function SetNativeTitlebar(enabled) {
    return $Call.ByID(1710067077, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {plugins$0.Manager | null} manager
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginManager(manager) {
    return $Call.ByID(3077852421, manager);
}

/**
 * @param {$models.ThemeSettings} theme
 * @returns {$CancellablePromise<$models.ThemeSettings>}
 */
export function SetTheme(theme) {
    return $Call.ByID(1442035638, theme).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowDownloadDir() {
    return $Call.ByID(1423237973);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartReticulum() {
    return $Call.ByID(905786083);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopReticulum() {
    return $Call.ByID(3051993617);
}

/**
 * @returns {$CancellablePromise<store$0.Store | null>}
 */
export function Store() {
    return $Call.ByID(3681528604).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * @param {string} chromeBg
 * @param {boolean} lightStatusIcons
 * @returns {$CancellablePromise<void>}
 */
export function SyncMobileChrome(chromeBg, lightStatusIcons) {
    return $Call.ByID(345790524, chromeBg, lightStatusIcons);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFullscreen() {
    return $Call.ByID(607083998);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.WindowState.createFrom;
const $$createType2 = rns$0.CommunityInterface.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.MicronWasmFetchResult.createFrom;
const $$createType5 = $models.AboutInfo.createFrom;
const $$createType6 = $models.BrowserPrefs.createFrom;
const $$createType7 = store$0.HistoryEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.DevLogEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.KeybindSettings.createFrom;
const $$createType12 = $models.PageResponse.createFrom;
const $$createType13 = $models.NetworkEntry.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.PageCacheStats.createFrom;
const $$createType16 = $models.RuntimeConfig.createFrom;
const $$createType17 = rns$0.Status.createFrom;
const $$createType18 = store$0.Health.createFrom;
const $$createType19 = store$0.TabSnapshot.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.ThemeSettings.createFrom;
const $$createType22 = $models.WindowChrome.createFrom;
const $$createType23 = $models.HistoryState.createFrom;
const $$createType24 = application$0.WebviewWindowOptions.createFrom;
const $$createType25 = $models.DownloadItem.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = rns$0.InterfaceInfo.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = nomadnet$0.Node.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = plugins$0.Manager.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $models.SettingsReset.createFrom;
const $$createType34 = store$0.Store.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
