// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BrowserService from "./browserservice.js";
import * as PluginHost from "./pluginhost.js";
export {
    BrowserService,
    PluginHost
};

export type {
    AboutInfo,
    BrowserPrefs,
    CommunityFetchResult,
    DevLogEntry,
    DownloadItem,
    HistoryEntry,
    HistoryState,
    KeybindSettings,
    MicronWasmFetchResult,
    NetworkEntry,
    PageCacheStats,
    PageResponse,
    PluginSummary,
    RuntimeConfig,
    SettingsReset,
    StoreHealth,
    TabSnapshot,
    ThemeSettings,
    WindowChrome,
    WindowState
} from "./models.js";
