// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BrowserService from "./browserservice.js";
export {
    BrowserService
};

export type {
    AboutInfo,
    BrowserPrefs,
    DevLogEntry,
    DownloadItem,
    HistoryEntry,
    HistoryState,
    KeybindSettings,
    MicronWasmFetchResult,
    NetworkEntry,
    PageResponse,
    RuntimeConfig,
    SettingsReset,
    StoreHealth,
    TabSnapshot,
    ThemeSettings,
    WindowChrome,
    WindowState
} from "./models.js";
