// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rns$0 from "../rns/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sandbox$0 from "../sandbox/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export interface AboutInfo {
    "appName": string;
    "version": string;
    "build": string;
    "license": string;
    "goVersion": string;
    "wailsVersion": string;
    "reticulumGo": string;
    "reticulumConfig": string;
    "dataPath": string;
}

/**
 * ActiveDownload is the live state of a tracked mesh file download, used to
 * drive the downloads panel's progress list, speed/ETA readouts, and the
 * badge counter on the download icon.
 */
export interface ActiveDownload {
    "id": string;
    "url": string;
    "name": string;
    "path"?: string;
    "received": number;
    "total": number;
    "status": DownloadStatus;
    "error"?: string;
    "attempt": number;
    "maxAttempts": number;
    "startedAt": number;
    "updatedAt": number;
}

/**
 * ApkShareInfo describes the installed Android package available for sharing.
 */
export interface ApkShareInfo {
    "available": boolean;
    "version": string;
    "size": number;
    "filename": string;
    "error"?: string;
}

/**
 * ApkShareSession describes an active local HTTP APK download session.
 */
export interface ApkShareSession {
    "active": boolean;
    "url": string;
    "qrDataURL"?: string;
    "error"?: string;
}

export interface BrowserPrefs {
    "openLinksInNewTab": boolean;
    "openLinksInNewWindow": boolean;
    "nativeTitlebar": boolean;
    "micronRenderer": string;
    "micronWasmEnabled": boolean;
    "micronWasmParserId": string;
    "docsLanguage": string;
    "uiLanguage": string;
    "discoverySlowMode": boolean;
    "mobileDevTools": boolean;
    "pageCacheEnabled": boolean;
    "tabHoverPreviews": boolean;
    "micronPreserveLayout": boolean;
    "initialSetupComplete": boolean;
    "settingsSectionsCollapsed": { [_ in string]?: boolean } | null;
}

export interface CheckStatus {
    "passed": boolean;
    "reason"?: string;
}

export interface CommunityFetchResult {
    "items": rns$0.CommunityInterface[] | null;
    "fromBundle": boolean;
}

export interface DevLogEntry {
    "time": number;
    "level": string;
    "message": string;
    "detail"?: string;
}

/**
 * DownloadHistoryClearResult reports whether the on-disk download list was cleared.
 */
export interface DownloadHistoryClearResult {
    "ok": boolean;
    "error"?: string;
}

export interface DownloadItem {
    "name": string;
    "path": string;
    "size": number;
    "modifiedAt": number;
}

/**
 * DownloadRetryResult reports whether a user-initiated download retry started.
 */
export interface DownloadRetryResult {
    "ok": boolean;
    "error"?: string;
}

/**
 * DownloadStatus is the lifecycle state of a tracked download shown in the
 * downloads UI.
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadStatusPending = "pending",
    DownloadStatusDownloading = "downloading",
    DownloadStatusRetrying = "retrying",
    DownloadStatusCompleted = "completed",
    DownloadStatusFailed = "failed",
    DownloadStatusCanceled = "canceled",
    DownloadStatusInterrupted = "interrupted",
};

export type HistoryEntry = store$0.HistoryEntry;

export interface HistoryState {
    "canGoBack": boolean;
    "canGoForward": boolean;
    "current": string;
}

export interface InitialSetupState {
    "needed": boolean;
    "suggestedCount": number;
}

export interface KeybindSettings {
    "bindings": { [_ in string]?: string } | null;
}

export interface MicronWasmFetchResult {
    "releaseTag": string;
    "wasmBase64": string;
    "sha256Hex": string;
}

export interface NetworkEntry {
    "time": number;
    "url": string;
    "nodeHash": string;
    "path": string;
    "durationMs": number;
    "bytes": number;
    "fromCache": boolean;
    "hops": number;
    "interface"?: string;
    "error"?: string;
    "source"?: string;
    "pluginId"?: string;
    "method"?: string;
    "statusCode"?: number;
}

export interface PageCacheStats {
    "entries": number;
    "max": number;
    "bytes": number;
    "maxBytes": number;
    "ramEntries": number;
    "diskEntries": number;
    "diskBytes": number;
    "diskMaxBytes": number;
}

export interface PageResponse {
    "url": string;
    "nodeHash": string;
    "path": string;
    "contentType": string;
    "html": string;
    "raw": string;
    "binaryB64"?: string;
    "pageFg"?: string;
    "pageBg"?: string;
    "durationMs": number;
    "fromCache": boolean;
    "cachedAt"?: number;
    "hops": number;
    "interface"?: string;
    "error"?: string;
    "errorKind"?: string;
}

export interface PluginHTTPRequest {
    "method": string;
    "url": string;
    "headers"?: { [_ in string]?: string } | null;
    "body"?: string;
}

export interface PluginHTTPResponse {
    "statusCode": number;
    "body": string;
}

export interface PluginInstallPreview {
    "id": string;
    "name": string;
    "version": string;
    "description"?: string;
    "permissions": string[] | null;
    "networkEndpoints": string[] | null;
    "requiresNetworkFetch": boolean;
    "signature": plugins$0.SignatureInfo;
    "security": plugins$0.SecurityAssessment;
    "i18nLocales": string[] | null;
}

export interface PluginSummary {
    "id": string;
    "name": string;
    "version": string;
    "description"?: string;
    "enabled": boolean;
    "error"?: string;
    "sizeBytes": number;
    "signature": plugins$0.SignatureInfo;
    "security": plugins$0.SecurityAssessment;
    "tampered": boolean;
    "grantedPermissions": string[] | null;
}

export interface RuntimeConfig {
    "publicMode": boolean;
    "serverMode": boolean;
    "profile": string;
    "profilePath": string;
}

/**
 * SandboxStatus describes process-level filesystem sandboxing.
 */
export type SandboxStatus = sandbox$0.Status;

export interface SelfCheckResult {
    "stackUp": CheckStatus;
    "configGood": CheckStatus;
    "dbGood": CheckStatus;
    "readWriteGood": CheckStatus;
    "downloadsGood": CheckStatus;
    "interfaces": CheckStatus;
    "discovery": CheckStatus;
    "pageFetch": CheckStatus;
    "allPassed": boolean;
    "meshEnabled": boolean;
}

export interface SettingsReset {
    "theme": ThemeSettings;
    "keybinds": KeybindSettings;
    "browserPrefs": BrowserPrefs;
}

export type StoreHealth = store$0.Health;

export type TabSnapshot = store$0.TabSnapshot;

export interface ThemeSettings {
    "mode": string;
    "accent": string;
    "fontFamily": string;
    "fontSize": number;
    "customTokens": { [_ in string]?: string } | null;
    "compactToolbar": boolean;
    "overlaySidebars": boolean;
}

export interface WindowChrome {
    "nativeTitlebar": boolean;
}

export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
}
