// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export interface AboutInfo {
    "appName": string;
    "version": string;
    "build": string;
    "license": string;
    "goVersion": string;
    "os": string;
    "arch": string;
    "wailsVersion": string;
    "reticulumConfig": string;
    "dataPath": string;
}

export interface BrowserPrefs {
    "openLinksInNewTab": boolean;
    "openLinksInNewWindow": boolean;
    "nativeTitlebar": boolean;
    "micronRenderer": string;
    "micronWasmEnabled": boolean;
    "micronWasmParserId": string;
}

export interface DevLogEntry {
    "time": number;
    "level": string;
    "message": string;
    "detail"?: string;
}

export interface DownloadItem {
    "name": string;
    "path": string;
    "size": number;
    "modifiedAt": number;
}

export type HistoryEntry = store$0.HistoryEntry;

export interface HistoryState {
    "canGoBack": boolean;
    "canGoForward": boolean;
    "current": string;
}

export interface KeybindSettings {
    "bindings": { [_ in string]?: string } | null;
}

export interface MicronWasmFetchResult {
    "releaseTag": string;
    "wasmBase64": string;
    "sha256Hex": string;
}

export interface NetworkEntry {
    "time": number;
    "url": string;
    "nodeHash": string;
    "path": string;
    "durationMs": number;
    "bytes": number;
    "fromCache": boolean;
    "hops": number;
    "error"?: string;
}

export interface PageResponse {
    "url": string;
    "nodeHash": string;
    "path": string;
    "contentType": string;
    "html": string;
    "raw": string;
    "pageFg"?: string;
    "pageBg"?: string;
    "durationMs": number;
    "fromCache": boolean;
    "cachedAt"?: number;
    "hops": number;
    "error"?: string;
    "errorKind"?: string;
}

export interface RuntimeConfig {
    "publicMode": boolean;
    "profile": string;
    "profilePath": string;
}

export interface SettingsReset {
    "theme": ThemeSettings;
    "keybinds": KeybindSettings;
    "browserPrefs": BrowserPrefs;
}

export type StoreHealth = store$0.Health;

export type TabSnapshot = store$0.TabSnapshot;

export interface ThemeSettings {
    "mode": string;
    "accent": string;
    "fontFamily": string;
    "fontSize": number;
    "customTokens": { [_ in string]?: string } | null;
    "compactToolbar": boolean;
}

export interface WindowChrome {
    "nativeTitlebar": boolean;
}

export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
}
