// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export class AboutInfo {
    /**
     * Creates a new AboutInfo instance.
     * @param {Partial<AboutInfo>} [$$source = {}] - The source object to create the AboutInfo.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("build" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["build"] = "";
        }
        if (!("license" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["license"] = "";
        }
        if (!("goVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["goVersion"] = "";
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("wailsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wailsVersion"] = "";
        }
        if (!("reticulumConfig" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reticulumConfig"] = "";
        }
        if (!("dataPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AboutInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AboutInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AboutInfo(/** @type {Partial<AboutInfo>} */($$parsedSource));
    }
}

export class BrowserPrefs {
    /**
     * Creates a new BrowserPrefs instance.
     * @param {Partial<BrowserPrefs>} [$$source = {}] - The source object to create the BrowserPrefs.
     */
    constructor($$source = {}) {
        if (!("openLinksInNewTab" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openLinksInNewTab"] = false;
        }
        if (!("openLinksInNewWindow" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openLinksInNewWindow"] = false;
        }
        if (!("nativeTitlebar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nativeTitlebar"] = false;
        }
        if (!("micronRenderer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["micronRenderer"] = "";
        }
        if (!("micronWasmEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["micronWasmEnabled"] = false;
        }
        if (!("micronWasmParserId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["micronWasmParserId"] = "";
        }
        if (!("docsLanguage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["docsLanguage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserPrefs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserPrefs}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserPrefs(/** @type {Partial<BrowserPrefs>} */($$parsedSource));
    }
}

export class DevLogEntry {
    /**
     * Creates a new DevLogEntry instance.
     * @param {Partial<DevLogEntry>} [$$source = {}] - The source object to create the DevLogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevLogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DevLogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevLogEntry(/** @type {Partial<DevLogEntry>} */($$parsedSource));
    }
}

export class DownloadItem {
    /**
     * Creates a new DownloadItem instance.
     * @param {Partial<DownloadItem>} [$$source = {}] - The source object to create the DownloadItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modifiedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadItem(/** @type {Partial<DownloadItem>} */($$parsedSource));
    }
}

export const HistoryEntry = store$0.HistoryEntry;

/**
 * @typedef {store$0.HistoryEntry} HistoryEntry
 */

export class HistoryState {
    /**
     * Creates a new HistoryState instance.
     * @param {Partial<HistoryState>} [$$source = {}] - The source object to create the HistoryState.
     */
    constructor($$source = {}) {
        if (!("canGoBack" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canGoBack"] = false;
        }
        if (!("canGoForward" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canGoForward"] = false;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryState(/** @type {Partial<HistoryState>} */($$parsedSource));
    }
}

export class KeybindSettings {
    /**
     * Creates a new KeybindSettings instance.
     * @param {Partial<KeybindSettings>} [$$source = {}] - The source object to create the KeybindSettings.
     */
    constructor($$source = {}) {
        if (!("bindings" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["bindings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeybindSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeybindSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField0_0($$parsedSource["bindings"]);
        }
        return new KeybindSettings(/** @type {Partial<KeybindSettings>} */($$parsedSource));
    }
}

export class MicronWasmFetchResult {
    /**
     * Creates a new MicronWasmFetchResult instance.
     * @param {Partial<MicronWasmFetchResult>} [$$source = {}] - The source object to create the MicronWasmFetchResult.
     */
    constructor($$source = {}) {
        if (!("releaseTag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseTag"] = "";
        }
        if (!("wasmBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wasmBase64"] = "";
        }
        if (!("sha256Hex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256Hex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MicronWasmFetchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MicronWasmFetchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MicronWasmFetchResult(/** @type {Partial<MicronWasmFetchResult>} */($$parsedSource));
    }
}

export class NetworkEntry {
    /**
     * Creates a new NetworkEntry instance.
     * @param {Partial<NetworkEntry>} [$$source = {}] - The source object to create the NetworkEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("nodeHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nodeHash"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("fromCache" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fromCache"] = false;
        }
        if (!("hops" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hops"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkEntry(/** @type {Partial<NetworkEntry>} */($$parsedSource));
    }
}

export class PageCacheStats {
    /**
     * Creates a new PageCacheStats instance.
     * @param {Partial<PageCacheStats>} [$$source = {}] - The source object to create the PageCacheStats.
     */
    constructor($$source = {}) {
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entries"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageCacheStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageCacheStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageCacheStats(/** @type {Partial<PageCacheStats>} */($$parsedSource));
    }
}

export class PageResponse {
    /**
     * Creates a new PageResponse instance.
     * @param {Partial<PageResponse>} [$$source = {}] - The source object to create the PageResponse.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("nodeHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nodeHash"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["html"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageFg"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageBg"] = undefined;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("fromCache" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fromCache"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["cachedAt"] = undefined;
        }
        if (!("hops" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hops"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorKind"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageResponse(/** @type {Partial<PageResponse>} */($$parsedSource));
    }
}

export class PluginSummary {
    /**
     * Creates a new PluginSummary instance.
     * @param {Partial<PluginSummary>} [$$source = {}] - The source object to create the PluginSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginSummary(/** @type {Partial<PluginSummary>} */($$parsedSource));
    }
}

export class RuntimeConfig {
    /**
     * Creates a new RuntimeConfig instance.
     * @param {Partial<RuntimeConfig>} [$$source = {}] - The source object to create the RuntimeConfig.
     */
    constructor($$source = {}) {
        if (!("publicMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["publicMode"] = false;
        }
        if (!("profile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile"] = "";
        }
        if (!("profilePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profilePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeConfig(/** @type {Partial<RuntimeConfig>} */($$parsedSource));
    }
}

export class SettingsReset {
    /**
     * Creates a new SettingsReset instance.
     * @param {Partial<SettingsReset>} [$$source = {}] - The source object to create the SettingsReset.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {ThemeSettings}
             */
            this["theme"] = (new ThemeSettings());
        }
        if (!("keybinds" in $$source)) {
            /**
             * @member
             * @type {KeybindSettings}
             */
            this["keybinds"] = (new KeybindSettings());
        }
        if (!("browserPrefs" in $$source)) {
            /**
             * @member
             * @type {BrowserPrefs}
             */
            this["browserPrefs"] = (new BrowserPrefs());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsReset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsReset}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("theme" in $$parsedSource) {
            $$parsedSource["theme"] = $$createField0_0($$parsedSource["theme"]);
        }
        if ("keybinds" in $$parsedSource) {
            $$parsedSource["keybinds"] = $$createField1_0($$parsedSource["keybinds"]);
        }
        if ("browserPrefs" in $$parsedSource) {
            $$parsedSource["browserPrefs"] = $$createField2_0($$parsedSource["browserPrefs"]);
        }
        return new SettingsReset(/** @type {Partial<SettingsReset>} */($$parsedSource));
    }
}

export const StoreHealth = store$0.Health;

/**
 * @typedef {store$0.Health} StoreHealth
 */

export const TabSnapshot = store$0.TabSnapshot;

/**
 * @typedef {store$0.TabSnapshot} TabSnapshot
 */

export class ThemeSettings {
    /**
     * Creates a new ThemeSettings instance.
     * @param {Partial<ThemeSettings>} [$$source = {}] - The source object to create the ThemeSettings.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("accent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accent"] = "";
        }
        if (!("fontFamily" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fontSize"] = 0;
        }
        if (!("customTokens" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["customTokens"] = {};
        }
        if (!("compactToolbar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["compactToolbar"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeSettings}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("customTokens" in $$parsedSource) {
            $$parsedSource["customTokens"] = $$createField4_0($$parsedSource["customTokens"]);
        }
        return new ThemeSettings(/** @type {Partial<ThemeSettings>} */($$parsedSource));
    }
}

export class WindowChrome {
    /**
     * Creates a new WindowChrome instance.
     * @param {Partial<WindowChrome>} [$$source = {}] - The source object to create the WindowChrome.
     */
    constructor($$source = {}) {
        if (!("nativeTitlebar" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nativeTitlebar"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowChrome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowChrome}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowChrome(/** @type {Partial<WindowChrome>} */($$parsedSource));
    }
}

export class WindowState {
    /**
     * Creates a new WindowState instance.
     * @param {Partial<WindowState>} [$$source = {}] - The source object to create the WindowState.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("maximized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["maximized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState(/** @type {Partial<WindowState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ThemeSettings.createFrom;
const $$createType2 = KeybindSettings.createFrom;
const $$createType3 = BrowserPrefs.createFrom;
