// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rns$0 from "../rns/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export interface AboutInfo {
    "appName": string;
    "version": string;
    "build": string;
    "license": string;
    "goVersion": string;
    "wailsVersion": string;
    "reticulumGo": string;
    "reticulumConfig": string;
    "dataPath": string;
}

/**
 * ActiveDownload is the live state of a tracked mesh file download, used to
 * drive the downloads panel's progress list, speed/ETA readouts, and the
 * badge counter on the download icon.
 */
export interface ActiveDownload {
    "id": string;
    "url": string;
    "name": string;
    "path"?: string;
    "received": number;
    "total": number;
    "status": DownloadStatus;
    "error"?: string;
    "startedAt": number;
    "updatedAt": number;
}

export interface BrowserPrefs {
    "openLinksInNewTab": boolean;
    "openLinksInNewWindow": boolean;
    "nativeTitlebar": boolean;
    "micronRenderer": string;
    "micronWasmEnabled": boolean;
    "micronWasmParserId": string;
    "docsLanguage": string;
    "uiLanguage": string;
    "discoverySlowMode": boolean;
    "mobileDevTools": boolean;
    "pageCacheEnabled": boolean;
    "tabHoverPreviews": boolean;
    "settingsSectionsCollapsed": { [_ in string]?: boolean } | null;
}

export interface CommunityFetchResult {
    "items": rns$0.CommunityInterface[] | null;
    "fromBundle": boolean;
}

export interface DevLogEntry {
    "time": number;
    "level": string;
    "message": string;
    "detail"?: string;
}

export interface DownloadItem {
    "name": string;
    "path": string;
    "size": number;
    "modifiedAt": number;
}

/**
 * DownloadStatus is the lifecycle state of a tracked download shown in the
 * downloads UI.
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadStatusPending = "pending",
    DownloadStatusDownloading = "downloading",
    DownloadStatusCompleted = "completed",
    DownloadStatusFailed = "failed",
    DownloadStatusCanceled = "canceled",
};

export type HistoryEntry = store$0.HistoryEntry;

export interface HistoryState {
    "canGoBack": boolean;
    "canGoForward": boolean;
    "current": string;
}

export interface KeybindSettings {
    "bindings": { [_ in string]?: string } | null;
}

export interface MicronWasmFetchResult {
    "releaseTag": string;
    "wasmBase64": string;
    "sha256Hex": string;
}

export interface NetworkEntry {
    "time": number;
    "url": string;
    "nodeHash": string;
    "path": string;
    "durationMs": number;
    "bytes": number;
    "fromCache": boolean;
    "hops": number;
    "interface"?: string;
    "error"?: string;
}

export interface PageCacheStats {
    "entries": number;
    "max": number;
}

export interface PageResponse {
    "url": string;
    "nodeHash": string;
    "path": string;
    "contentType": string;
    "html": string;
    "raw": string;
    "pageFg"?: string;
    "pageBg"?: string;
    "durationMs": number;
    "fromCache": boolean;
    "cachedAt"?: number;
    "hops": number;
    "interface"?: string;
    "error"?: string;
    "errorKind"?: string;
}

export interface PluginSummary {
    "id": string;
    "name": string;
    "version": string;
    "description"?: string;
    "enabled": boolean;
    "error"?: string;
}

export interface RuntimeConfig {
    "publicMode": boolean;
    "serverMode": boolean;
    "profile": string;
    "profilePath": string;
}

export interface SettingsReset {
    "theme": ThemeSettings;
    "keybinds": KeybindSettings;
    "browserPrefs": BrowserPrefs;
}

export type StoreHealth = store$0.Health;

export type TabSnapshot = store$0.TabSnapshot;

export interface ThemeSettings {
    "mode": string;
    "accent": string;
    "fontFamily": string;
    "fontSize": number;
    "customTokens": { [_ in string]?: string } | null;
    "compactToolbar": boolean;
}

export interface WindowChrome {
    "nativeTitlebar": boolean;
}

export interface WindowState {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
}
