// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DisablePlugin(id: string): $CancellablePromise<void> {
    return $Call.ByID(3180758000, id);
}

export function EmitPluginEvent(pluginID: string, event: string, data: any): $CancellablePromise<void> {
    return $Call.ByID(3070164839, pluginID, event, data);
}

export function EnablePlugin(id: string): $CancellablePromise<void> {
    return $Call.ByID(2868525969, id);
}

export function GetContributions(): $CancellablePromise<plugins$0.ContributionsView> {
    return $Call.ByID(4107853986);
}

export function GetPlugin(id: string): $CancellablePromise<plugins$0.InstalledPlugin> {
    return $Call.ByID(3059097876, id);
}

export function GetPluginStorage(id: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1097936333, id, key);
}

export function InstallPluginFromDir(path: string): $CancellablePromise<plugins$0.InstalledPlugin> {
    return $Call.ByID(2184559862, path);
}

export function InstallPluginFromZip(path: string): $CancellablePromise<plugins$0.InstalledPlugin> {
    return $Call.ByID(116692350, path);
}

export function InvokeCommand(pluginID: string, commandID: string, args: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(309676130, pluginID, commandID, args);
}

export function ListPlugins(): $CancellablePromise<$models.PluginSummary[] | null> {
    return $Call.ByID(4090050199);
}

export function PluginsDir(): $CancellablePromise<string> {
    return $Call.ByID(3400877522);
}

export function SetPluginStorage(id: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(295660081, id, key, value);
}

export function UninstallPlugin(id: string): $CancellablePromise<void> {
    return $Call.ByID(114026790, id);
}
