// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(id) {
    return $Call.ByID(3180758000, id);
}

/**
 * @param {string} pluginID
 * @param {string} event
 * @param {any} data
 * @returns {$CancellablePromise<void>}
 */
export function EmitPluginEvent(pluginID, event, data) {
    return $Call.ByID(3070164839, pluginID, event, data);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(id) {
    return $Call.ByID(2868525969, id);
}

/**
 * @returns {$CancellablePromise<plugins$0.ContributionsView>}
 */
export function GetContributions() {
    return $Call.ByID(4107853986).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<plugins$0.InstalledPlugin>}
 */
export function GetPlugin(id) {
    return $Call.ByID(3059097876, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetPluginStorage(id, key) {
    return $Call.ByID(1097936333, id, key);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<plugins$0.InstalledPlugin>}
 */
export function InstallPluginFromDir(path) {
    return $Call.ByID(2184559862, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<plugins$0.InstalledPlugin>}
 */
export function InstallPluginFromZip(path) {
    return $Call.ByID(116692350, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pluginID
 * @param {string} commandID
 * @param {{ [_ in string]?: string }} args
 * @returns {$CancellablePromise<void>}
 */
export function InvokeCommand(pluginID, commandID, args) {
    return $Call.ByID(309676130, pluginID, commandID, args);
}

/**
 * @returns {$CancellablePromise<$models.PluginSummary[]>}
 */
export function ListPlugins() {
    return $Call.ByID(4090050199).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PluginsDir() {
    return $Call.ByID(3400877522);
}

/**
 * @param {string} id
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetPluginStorage(id, key, value) {
    return $Call.ByID(295660081, id, key, value);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UninstallPlugin(id) {
    return $Call.ByID(114026790, id);
}

// Private type creation functions
const $$createType0 = plugins$0.ContributionsView.createFrom;
const $$createType1 = plugins$0.InstalledPlugin.createFrom;
const $$createType2 = $models.PluginSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
