// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bool is an optional bool value.
 */
export type Bool = Var<boolean>;

/**
 * Var is a generic optional value that tracks whether it has been set.
 */
export interface Var<T> {
}
