// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Health {
    "ok": boolean;
    "kind"?: string;
    "detail"?: string;
    "path": string;
}

export interface HistoryEntry {
    "id": number;
    "url": string;
    "title": string;
    "nodeHash": string;
    "visitedAt": number;
}

export interface TabSnapshot {
    "id": string;
    "title": string;
    "url": string;
    "active": boolean;
    "pinned"?: boolean;
    "html"?: string;
    "contentType"?: string;
    "error"?: string;
    "durationMs"?: number;
    "lastRaw"?: string;
    "pageFg"?: string;
    "pageBg"?: string;
}
