//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../../../../renbrowser/internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nomadnet$0 from "../../../../../renbrowser/internal/nomadnet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../../../../../renbrowser/internal/plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../../../../renbrowser/internal/store/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "network:entry": $$createType0,
        "node:discovered": $$createType2,
        "page:error": $$createType3,
        "page:loaded": $$createType3,
        "plugin:loaded": $$createType4,
        "plugin:scheme": $$createType5,
        "plugin:unloaded": $$createType4,
        "runtime:config": $$createType6,
        "store:health": $$createType7,
        "theme:changed": $$createType8,
        "window:chrome": $$createType9,
    }));
}

// Private type creation functions
const $$createType0 = app$0.NetworkEntry.createFrom;
const $$createType1 = nomadnet$0.Node.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = app$0.PageResponse.createFrom;
const $$createType4 = plugins$0.Manifest.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = app$0.RuntimeConfig.createFrom;
const $$createType7 = store$0.Health.createFrom;
const $$createType8 = app$0.ThemeSettings.createFrom;
const $$createType9 = app$0.WindowChrome.createFrom;

configure();
