// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Node {
    "hash": string;
    "name": string;
    "hops": number;
    "enabled": boolean;
    "timestamp": number;
    "maxSizeKb": number;
    "lastSeen": number;
}

/**
 * WakePrepResult summarizes what PrepareForWake invalidated.
 */
export interface WakePrepResult {
    "droppedLinks": number;
    "expiredPaths": number;
}
