// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Node {
    /**
     * Creates a new Node instance.
     * @param {Partial<Node>} [$$source = {}] - The source object to create the Node.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hops" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hops"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("maxSizeKb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSizeKb"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastSeen"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Node}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Node(/** @type {Partial<Node>} */($$parsedSource));
    }
}
