FROM gcr.io/distroless/static-debian12@sha256:9c346e4be81b5ca7ff31a0d89eaeade58b0f95cfd3baed1f36083ddb47ca3160

COPY server /server
COPY frontend-dist /frontend/dist

EXPOSE 8080

ENV WAILS_SERVER_HOST=0.0.0.0
ENV WAILS_SERVER_PORT=8080
ENV REN_BROWSER_TRUST_PROXY=false
ENV REN_BROWSER_BASE_PATH=

ENTRYPOINT ["/server"]
