FROM gcr.io/distroless/static-debian12

COPY server /server
COPY frontend-dist /frontend/dist

EXPOSE 8080

ENV WAILS_SERVER_HOST=0.0.0.0
ENV WAILS_SERVER_PORT=8080
ENV REN_BROWSER_TRUST_PROXY=false
ENV REN_BROWSER_BASE_PATH=

ENTRYPOINT ["/server"]
