// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FieldInput {
    /**
     * Creates a new FieldInput instance.
     * @param {Partial<FieldInput>} [$$source = {}] - The source object to create the FieldInput.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("checked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FieldInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FieldInput(/** @type {Partial<FieldInput>} */($$parsedSource));
    }
}
