// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FieldInput {
    "type": string;
    "name": string;
    "value": string;
    "checked": boolean;
}
