// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status describes process-level filesystem sandboxing for the settings UI.
 */
export interface Status {
    "type": string;
    "enabled": boolean;
    "requested": boolean;
    "supported": boolean;
    "auto": boolean;
    "disabledByEnv": boolean;
    "reason"?: string;
    "abi"?: number;
    "seccompEnabled": boolean;
    "seccompSupported": boolean;
    "seccompReason"?: string;
    "inFlatpak": boolean;
    "inAppImage": boolean;
    "inContainer": boolean;
    "containerRuntime"?: string;
    "webkitSandbox": string;
    "webkitSandboxNote"?: string;
    "onAndroid": boolean;
}
