// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommunityInterface {
    /**
     * Creates a new CommunityInterface instance.
     * @param {Partial<CommunityInterface>} [$$source = {}] - The source object to create the CommunityInterface.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("typeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["typeName"] = "";
        }
        if (!("network" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["network"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["port"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommunityInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommunityInterface}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommunityInterface(/** @type {Partial<CommunityInterface>} */($$parsedSource));
    }
}

export class InterfaceInfo {
    /**
     * Creates a new InterfaceInfo instance.
     * @param {Partial<InterfaceInfo>} [$$source = {}] - The source object to create the InterfaceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (!("txBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytes"] = 0;
        }
        if (!("rxBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterfaceInfo(/** @type {Partial<InterfaceInfo>} */($$parsedSource));
    }
}

export class Stack {
    /**
     * Creates a new Stack instance.
     * @param {Partial<Stack>} [$$source = {}] - The source object to create the Stack.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stack(/** @type {Partial<Stack>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (!("nodeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nodeCount"] = 0;
        }
        if (!("interfaceCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interfaceCount"] = 0;
        }
        if (!("interfacesOnline" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interfacesOnline"] = 0;
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}
