// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CommunityInterface {
    "id": number;
    "name": string;
    "type": string;
    "typeName": string;
    "network": string;
    "host": string;
    "port": number | null;
    "status": string;
    "config": string;
    "installed": boolean;
}

/**
 * IdentityRecord describes a stored transport identity for the settings UI.
 */
export interface IdentityRecord {
    "id": string;
    "name": string;
    "hash": string;
    "createdAt": number;
    "active": boolean;
}

export interface InterfaceInfo {
    "name": string;
    "type": string;
    "enabled": boolean;
    "online": boolean;
    "txBytes": number;
    "rxBytes": number;
}

export interface Stack {
}

export interface Status {
    "online": boolean;
    "nodeCount": number;
    "interfaceCount": number;
    "interfacesOnline": number;
    "configPath": string;
    "enableTransport": boolean;
    "shareInstance": boolean;
    "connectedToSharedInstance": boolean;
    "sharedInstanceMode": string;
    "transportActive": boolean;
}
