// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    App,
    AutostartManager,
    BackdropType,
    BackgroundType,
    BrowserManager,
    ButtonState,
    ClipboardManager,
    ContextMenuManager,
    CoreWebView2PermissionKind,
    CoreWebView2PermissionState,
    DialogManager,
    EnvironmentManager,
    EventManager,
    GlobalShortcutManager,
    KeyBindingManager,
    LinuxMenuStyle,
    LinuxWindow,
    MacAppearanceType,
    MacBackdrop,
    MacLiquidGlass,
    MacLiquidGlassStyle,
    MacTitleBar,
    MacToolbarStyle,
    MacWebviewPreferences,
    MacWindow,
    MacWindowCollectionBehavior,
    MacWindowLevel,
    MacWindowTabbingMode,
    Menu,
    MenuBarTheme,
    MenuManager,
    NSVisualEffectMaterial,
    Permission,
    PermissionType,
    RGBA,
    Rect,
    Screen,
    ScreenManager,
    Size,
    SystemTrayManager,
    TextTheme,
    Theme,
    ThemeSettings,
    WebviewGpuPolicy,
    WebviewWindowOptions,
    WindowManager,
    WindowStartPosition,
    WindowState,
    WindowTheme,
    WindowsWindow
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.Window} Window
 */
