// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as optional$0 from "../../internal/optional/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../../log/slog/models.js";

export interface App {
    /**
     * Manager pattern for organized API
     */
    "Window": WindowManager | null;
    "ContextMenu": ContextMenuManager | null;
    "KeyBinding": KeyBindingManager | null;
    "Browser": BrowserManager | null;
    "Env": EnvironmentManager | null;
    "Dialog": DialogManager | null;
    "Event": EventManager | null;
    "Menu": MenuManager | null;
    "Screen": ScreenManager | null;
    "Clipboard": ClipboardManager | null;
    "SystemTray": SystemTrayManager | null;
    "Autostart": AutostartManager | null;
    "GlobalShortcut": GlobalShortcutManager | null;
    "Updater": updater$0.Updater | null;
    "Logger": slog$0.Logger | null;
}

/**
 * AutostartManager provides cross-platform control over whether the
 * application launches when the user logs in.
 * 
 * Registration takes effect on the next login, not immediately.
 * 
 * Platform behaviour:
 * 
 *   - macOS 13+ (bundled .app):  SMAppService.mainAppService — works for
 *     sandboxed and Mac-App-Store apps, no TCC automation prompt.
 *   - macOS (older or unbundled): a LaunchAgent plist is written to
 *     ~/Library/LaunchAgents/.
 *   - Windows: a value is added under
 *     HKCU\Software\Microsoft\Windows\CurrentVersion\Run.
 *   - Linux: an .desktop file is written to $XDG_CONFIG_HOME/autostart/
 *     (defaulting to ~/.config/autostart/).
 *   - Android / iOS / server builds: ErrAutostartNotSupported.
 */
export interface AutostartManager {
}

export enum BackdropType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Auto = 0,
    None = 1,
    Mica = 2,
    Acrylic = 3,
    Tabbed = 4,
};

export enum BackgroundType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    BackgroundTypeSolid = 0,
    BackgroundTypeTransparent = 1,
    BackgroundTypeTranslucent = 2,
};

/**
 * BrowserManager manages browser-related operations
 */
export interface BrowserManager {
}

export enum ButtonState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ButtonEnabled = 0,
    ButtonDisabled = 1,
    ButtonHidden = 2,
};

/**
 * ClipboardManager manages clipboard operations
 */
export interface ClipboardManager {
}

/**
 * ContextMenuManager manages all context menu operations
 */
export interface ContextMenuManager {
}

export enum CoreWebView2PermissionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CoreWebView2PermissionKindUnknownPermission = 0,
    CoreWebView2PermissionKindMicrophone = 1,
    CoreWebView2PermissionKindCamera = 2,
    CoreWebView2PermissionKindGeolocation = 3,
    CoreWebView2PermissionKindNotifications = 4,
    CoreWebView2PermissionKindOtherSensors = 5,
    CoreWebView2PermissionKindClipboardRead = 6,
};

export enum CoreWebView2PermissionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    CoreWebView2PermissionStateDefault = 0,
    CoreWebView2PermissionStateAllow = 1,
    CoreWebView2PermissionStateDeny = 2,
};

/**
 * DialogManager manages dialog-related operations
 */
export interface DialogManager {
}

/**
 * EnvironmentManager manages environment-related operations
 */
export interface EnvironmentManager {
}

/**
 * EventManager manages event-related operations
 */
export interface EventManager {
}

/**
 * GlobalShortcutManager manages application-wide (global) keyboard shortcuts.
 * 
 * Unlike menu accelerators or [KeyBindingManager] - which only fire while a
 * Wails window has focus - a global shortcut fires regardless of which
 * application is currently focused, as long as the Wails application is
 * running.
 * 
 * Global shortcuts are owned by the application, not by an individual window.
 * Registering the same accelerator twice within the same application is
 * reported as an error and the original binding is preserved; see [Register].
 * 
 * Shortcuts may be registered before [App.Run] is called: the binding with the
 * operating system is then deferred until the application starts.
 */
export interface GlobalShortcutManager {
}

/**
 * KeyBindingManager manages all key binding operations
 */
export interface KeyBindingManager {
}

/**
 * LinuxMenuStyle defines how the application menu is displayed on Linux (GTK4 only).
 * On GTK3 builds, this option is ignored and MenuBar style is always used.
 */
export enum LinuxMenuStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * LinuxMenuStyleMenuBar displays a traditional menu bar below the title bar (default)
     */
    LinuxMenuStyleMenuBar = 0,

    /**
     * LinuxMenuStylePrimaryMenu displays a primary menu button in the header bar (GNOME style)
     */
    LinuxMenuStylePrimaryMenu = 1,
};

/**
 * LinuxWindow specific to Linux windows
 */
export interface LinuxWindow {
    /**
     * Icon Sets up the icon representing the window. This icon is used when the window is minimized
     * (also known as iconified).
     */
    "Icon": string | null;

    /**
     * WindowIsTranslucent sets the window's background to transparent when enabled.
     */
    "WindowIsTranslucent": boolean;

    /**
     * WebviewGpuPolicy used for determining the hardware acceleration policy for the webview.
     *   - WebviewGpuPolicyAlways
     *   - WebviewGpuPolicyOnDemand
     *   - WebviewGpuPolicyNever
     * 
     * Due to https://github.com/wailsapp/wails/issues/2977, if options.Linux is nil
     * in the call to wails.Run(), WebviewGpuPolicy is set by default to WebviewGpuPolicyNever.
     * Client code may override this behavior by passing a non-nil Options and set
     * WebviewGpuPolicy as needed.
     */
    "WebviewGpuPolicy": WebviewGpuPolicy;

    /**
     * WindowDidMoveDebounceMS is the debounce time in milliseconds for the WindowDidMove event
     */
    "WindowDidMoveDebounceMS": number;

    /**
     * Menu is the window's menu
     */
    "Menu": Menu | null;

    /**
     * MenuStyle controls how the menu is displayed (GTK4 only, ignored on GTK3)
     */
    "MenuStyle": LinuxMenuStyle;
}

/**
 * MacAppearanceType is a type of Appearance for Cocoa windows
 */
export enum MacAppearanceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * DefaultAppearance uses the default system value
     */
    DefaultAppearance = "",

    /**
     * NSAppearanceNameAqua - The standard light system appearance.
     */
    NSAppearanceNameAqua = "NSAppearanceNameAqua",

    /**
     * NSAppearanceNameDarkAqua - The standard dark system appearance.
     */
    NSAppearanceNameDarkAqua = "NSAppearanceNameDarkAqua",

    /**
     * NSAppearanceNameVibrantLight - The light vibrant appearance
     */
    NSAppearanceNameVibrantLight = "NSAppearanceNameVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastAqua - A high-contrast version of the standard light system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastAqua = "NSAppearanceNameAccessibilityHighContrastAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastDarkAqua - A high-contrast version of the standard dark system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastDarkAqua = "NSAppearanceNameAccessibilityHighContrastDarkAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantLight - A high-contrast version of the light vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantLight = "NSAppearanceNameAccessibilityHighContrastVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantDark - A high-contrast version of the dark vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantDark = "NSAppearanceNameAccessibilityHighContrastVibrantDark",
};

/**
 * MacBackdrop is the backdrop type for macOS
 */
export enum MacBackdrop {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacBackdropNormal - The default value. The window will have a normal opaque background.
     */
    MacBackdropNormal = 0,

    /**
     * MacBackdropTransparent - The window will have a transparent background, with the content underneath it being visible
     */
    MacBackdropTransparent = 1,

    /**
     * MacBackdropTranslucent - The window will have a translucent background, with the content underneath it being "fuzzy" or "frosted"
     */
    MacBackdropTranslucent = 2,

    /**
     * MacBackdropLiquidGlass - The window will use Apple's Liquid Glass effect (macOS 15.0+ with fallback to translucent)
     */
    MacBackdropLiquidGlass = 3,
};

/**
 * MacLiquidGlass contains configuration for the Liquid Glass effect
 */
export interface MacLiquidGlass {
    /**
     * Style of the glass effect
     */
    "Style": MacLiquidGlassStyle;

    /**
     * Material to use for NSVisualEffectView (when NSGlassEffectView is not available)
     * Set to NSVisualEffectMaterialAuto to use automatic selection based on Style
     */
    "Material": NSVisualEffectMaterial;

    /**
     * Corner radius for the glass effect (0 for square corners)
     */
    "CornerRadius": number;

    /**
     * Tint color for the glass (optional, nil for no tint)
     */
    "TintColor": RGBA | null;

    /**
     * Group identifier for merging multiple glass windows
     */
    "GroupID": string;

    /**
     * Spacing between grouped glass elements (in points)
     */
    "GroupSpacing": number;
}

/**
 * MacLiquidGlassStyle defines the style of the Liquid Glass effect
 */
export enum MacLiquidGlassStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * LiquidGlassStyleAutomatic - System determines the best style
     */
    LiquidGlassStyleAutomatic = 0,

    /**
     * LiquidGlassStyleLight - Light glass appearance
     */
    LiquidGlassStyleLight = 1,

    /**
     * LiquidGlassStyleDark - Dark glass appearance
     */
    LiquidGlassStyleDark = 2,

    /**
     * LiquidGlassStyleVibrant - Vibrant glass with enhanced effects
     */
    LiquidGlassStyleVibrant = 3,
};

/**
 * MacTitleBar contains options for the Mac titlebar
 */
export interface MacTitleBar {
    /**
     * AppearsTransparent will make the titlebar transparent
     */
    "AppearsTransparent": boolean;

    /**
     * Hide will hide the titlebar
     */
    "Hide": boolean;

    /**
     * HideTitle will hide the title
     */
    "HideTitle": boolean;

    /**
     * FullSizeContent will extend the window content to the full size of the window
     */
    "FullSizeContent": boolean;

    /**
     * UseToolbar will use a toolbar instead of a titlebar
     */
    "UseToolbar": boolean;

    /**
     * HideToolbarSeparator will hide the toolbar separator
     */
    "HideToolbarSeparator": boolean;

    /**
     * ShowToolbarWhenFullscreen will keep the toolbar visible when the window is in fullscreen mode
     */
    "ShowToolbarWhenFullscreen": boolean;

    /**
     * ToolbarStyle is the style of toolbar to use
     */
    "ToolbarStyle": MacToolbarStyle;
}

/**
 * MacToolbarStyle is the style of toolbar for macOS
 */
export enum MacToolbarStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacToolbarStyleAutomatic - The default value. The style will be determined by the window's given configuration
     */
    MacToolbarStyleAutomatic = 0,

    /**
     * MacToolbarStyleExpanded - The toolbar will appear below the window title
     */
    MacToolbarStyleExpanded = 1,

    /**
     * MacToolbarStylePreference - The toolbar will appear below the window title and the items in the toolbar will attempt to have equal widths when possible
     */
    MacToolbarStylePreference = 2,

    /**
     * MacToolbarStyleUnified - The window title will appear inline with the toolbar when visible
     */
    MacToolbarStyleUnified = 3,

    /**
     * MacToolbarStyleUnifiedCompact - Same as MacToolbarStyleUnified, but with reduced margins in the toolbar allowing more focus to be on the contents of the window
     */
    MacToolbarStyleUnifiedCompact = 4,
};

/**
 * MacWebviewPreferences contains preferences for the Mac webview
 */
export interface MacWebviewPreferences {
    /**
     * TabFocusesLinks will enable tabbing to links
     */
    "TabFocusesLinks": optional$0.Bool;

    /**
     * TextInteractionEnabled will enable text interaction
     */
    "TextInteractionEnabled": optional$0.Bool;

    /**
     * FullscreenEnabled will enable fullscreen
     */
    "FullscreenEnabled": optional$0.Bool;

    /**
     * AllowsBackForwardNavigationGestures enables horizontal swipe gestures for back/forward navigation
     */
    "AllowsBackForwardNavigationGestures": optional$0.Bool;

    /**
     * AllowsMagnification enables pinch-to-zoom on the webview
     */
    "AllowsMagnification": optional$0.Bool;

    /**
     * AllowsAirPlayForMediaPlayback enables AirPlay media playback
     */
    "AllowsAirPlayForMediaPlayback": optional$0.Bool;

    /**
     * JavaScriptCanOpenWindowsAutomatically allows JS to open windows without a user gesture
     */
    "JavaScriptCanOpenWindowsAutomatically": optional$0.Bool;

    /**
     * MinimumFontSize sets the minimum font size in points
     */
    "MinimumFontSize": optional$0.Var<number>;

    /**
     * ApplicationNameForUserAgent overrides the application name portion of the user agent string.
     * Leave empty to use the default "wails.io" suffix.
     */
    "ApplicationNameForUserAgent": string;

    /**
     * EnableAutoplayWithoutUserAction allows media to start playing automatically
     * without requiring a user gesture. Maps to WKWebViewConfiguration.mediaTypesRequiringUserActionForPlayback.
     */
    "EnableAutoplayWithoutUserAction": optional$0.Bool;
}

/**
 * MacWindow contains macOS specific options for Webview Windows
 */
export interface MacWindow {
    /**
     * Backdrop is the backdrop type for the window
     */
    "Backdrop": MacBackdrop;

    /**
     * DisableShadow will disable the window shadow
     */
    "DisableShadow": boolean;

    /**
     * TitleBar contains options for the Mac titlebar
     */
    "TitleBar": MacTitleBar;

    /**
     * Appearance is the appearance type for the window
     */
    "Appearance": MacAppearanceType;

    /**
     * InvisibleTitleBarHeight defines the height of an invisible titlebar which responds to dragging
     */
    "InvisibleTitleBarHeight": number;

    /**
     * Maps events from platform specific to common event types
     */
    "EventMapping": { [_ in events$0.WindowEventType]?: events$0.WindowEventType } | null;

    /**
     * EnableFraudulentWebsiteWarnings will enable warnings for fraudulent websites.
     * Default: false
     */
    "EnableFraudulentWebsiteWarnings": boolean;

    /**
     * WebviewPreferences contains preferences for the webview
     */
    "WebviewPreferences": MacWebviewPreferences;

    /**
     * WindowLevel sets the window level to control the order of windows in the screen
     */
    "WindowLevel": MacWindowLevel;

    /**
     * CollectionBehavior controls how the window behaves across macOS Spaces and fullscreen
     */
    "CollectionBehavior": MacWindowCollectionBehavior;

    /**
     * TabbingMode sets the window tabbing mode (macOS 10.12+)
     */
    "TabbingMode": MacWindowTabbingMode;

    /**
     * LiquidGlass contains configuration for the Liquid Glass effect
     */
    "LiquidGlass": MacLiquidGlass;

    /**
     * DisableEscapeExitsFullscreen prevents the Escape key from exiting fullscreen mode.
     * When true, Esc keypresses are swallowed while the window is fullscreen, allowing
     * web content (e.g. modals with Esc-to-close behaviour) to handle Esc directly.
     * Default false preserves standard macOS behaviour where Esc exits fullscreen.
     */
    "DisableEscapeExitsFullscreen": boolean;
}

/**
 * MacWindowCollectionBehavior controls window behavior across macOS Spaces and fullscreen.
 * These correspond to NSWindowCollectionBehavior bitmask values and can be combined using bitwise OR.
 * For example: MacWindowCollectionBehaviorCanJoinAllSpaces | MacWindowCollectionBehaviorFullScreenAuxiliary
 */
export enum MacWindowCollectionBehavior {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacWindowCollectionBehaviorDefault is zero value - when set, FullScreenPrimary is used for backwards compatibility
     */
    MacWindowCollectionBehaviorDefault = 0,

    /**
     * MacWindowCollectionBehaviorCanJoinAllSpaces allows window to appear on all Spaces
     * 1
     */
    MacWindowCollectionBehaviorCanJoinAllSpaces = 1,

    /**
     * MacWindowCollectionBehaviorMoveToActiveSpace moves window to active Space when shown
     * 2
     */
    MacWindowCollectionBehaviorMoveToActiveSpace = 2,

    /**
     * MacWindowCollectionBehaviorManaged is the default managed window behavior
     * 4
     */
    MacWindowCollectionBehaviorManaged = 4,

    /**
     * MacWindowCollectionBehaviorTransient marks window as temporary/transient
     * 8
     */
    MacWindowCollectionBehaviorTransient = 8,

    /**
     * MacWindowCollectionBehaviorStationary keeps window stationary during Space switches
     * 16
     */
    MacWindowCollectionBehaviorStationary = 16,

    /**
     * MacWindowCollectionBehaviorParticipatesInCycle includes window in Cmd+` cycling (default for normal windows)
     * 32
     */
    MacWindowCollectionBehaviorParticipatesInCycle = 32,

    /**
     * MacWindowCollectionBehaviorIgnoresCycle excludes window from Cmd+` cycling
     * 64
     */
    MacWindowCollectionBehaviorIgnoresCycle = 64,

    /**
     * MacWindowCollectionBehaviorFullScreenPrimary allows the window to enter fullscreen
     * 128
     */
    MacWindowCollectionBehaviorFullScreenPrimary = 128,

    /**
     * MacWindowCollectionBehaviorFullScreenAuxiliary allows window to overlay fullscreen apps
     * 256
     */
    MacWindowCollectionBehaviorFullScreenAuxiliary = 256,

    /**
     * MacWindowCollectionBehaviorFullScreenNone prevents window from entering fullscreen (macOS 10.7+)
     * 512
     */
    MacWindowCollectionBehaviorFullScreenNone = 512,

    /**
     * MacWindowCollectionBehaviorFullScreenAllowsTiling allows side-by-side tiling in fullscreen (macOS 10.11+)
     * 2048
     */
    MacWindowCollectionBehaviorFullScreenAllowsTiling = 2048,

    /**
     * MacWindowCollectionBehaviorFullScreenDisallowsTiling prevents tiling in fullscreen (macOS 10.11+)
     * 4096
     */
    MacWindowCollectionBehaviorFullScreenDisallowsTiling = 4096,
};

export enum MacWindowLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MacWindowLevelNormal = "normal",
    MacWindowLevelFloating = "floating",
    MacWindowLevelTornOffMenu = "tornOffMenu",
    MacWindowLevelModalPanel = "modalPanel",
    MacWindowLevelMainMenu = "mainMenu",
    MacWindowLevelStatus = "status",
    MacWindowLevelPopUpMenu = "popUpMenu",
    MacWindowLevelScreenSaver = "screenSaver",
};

/**
 * MacWindowTabbingMode controls window tabbing behavior (macOS 10.12+).
 * Values map to NSWindowTabbingMode (offset by 1 so the zero value is an "unset" sentinel).
 */
export enum MacWindowTabbingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MacWindowTabbingModeDefault is the zero-value sentinel meaning "not explicitly set".
     * At runtime it resolves to Disallowed.
     */
    MacWindowTabbingModeDefault = 0,

    /**
     * MacWindowTabbingModeAutomatic allows the system to determine tabbing behavior
     */
    MacWindowTabbingModeAutomatic = 1,

    /**
     * MacWindowTabbingModePreferred indicates the window prefers to be in tabbing mode
     */
    MacWindowTabbingModePreferred = 2,

    /**
     * MacWindowTabbingModeDisallowed prevents the window from being tabbed
     */
    MacWindowTabbingModeDisallowed = 3,
};

export interface Menu {
}

export interface MenuBarTheme {
    /**
     * Default is the default theme
     */
    "Default": TextTheme | null;

    /**
     * Hover defines the theme to use when the menu item is hovered
     */
    "Hover": TextTheme | null;

    /**
     * Selected defines the theme to use when the menu item is selected
     */
    "Selected": TextTheme | null;
}

/**
 * MenuManager manages menu-related operations
 */
export interface MenuManager {
}

/**
 * NSVisualEffectMaterial represents the NSVisualEffectMaterial enum for macOS
 */
export enum NSVisualEffectMaterial {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * NSVisualEffectMaterial values from macOS SDK
     */
    NSVisualEffectMaterialAppearanceBased = 0,
    NSVisualEffectMaterialLight = 1,
    NSVisualEffectMaterialDark = 2,
    NSVisualEffectMaterialTitlebar = 3,
    NSVisualEffectMaterialSelection = 4,
    NSVisualEffectMaterialMenu = 5,
    NSVisualEffectMaterialPopover = 6,
    NSVisualEffectMaterialSidebar = 7,
    NSVisualEffectMaterialHeaderView = 10,
    NSVisualEffectMaterialSheet = 11,
    NSVisualEffectMaterialWindowBackground = 12,
    NSVisualEffectMaterialHUDWindow = 13,
    NSVisualEffectMaterialFullScreenUI = 15,
    NSVisualEffectMaterialToolTip = 17,
    NSVisualEffectMaterialContentBackground = 18,
    NSVisualEffectMaterialUnderWindowBackground = 21,
    NSVisualEffectMaterialUnderPageBackground = 22,

    /**
     * Use auto-selection based on Style
     */
    NSVisualEffectMaterialAuto = -1,
};

/**
 * Permission is the policy applied to a PermissionType. The values are kept in
 * step with the native WebView2 permission-state ABI (Default=0, Allow=1,
 * Deny=2) so the Windows backend needs no translation.
 */
export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * PermissionDefault uses the platform's native handling and is the zero
     * value. On macOS (TCC) and Windows (WebView2) this presents the OS/webview
     * permission prompt to the user. Linux/WebKitGTK has no prompt mechanism,
     * so media capture (camera/microphone) is allowed — restoring getUserMedia
     * for app content — and other capabilities are denied.
     */
    PermissionDefault = 0,

    /**
     * PermissionAllow grants the capability without prompting.
     */
    PermissionAllow = 1,

    /**
     * PermissionDeny denies the capability without prompting.
     */
    PermissionDeny = 2,
};

/**
 * PermissionType identifies a capability that web content can request from
 * the webview (camera, microphone, …). It is the cross-platform equivalent of
 * the platform-specific permission-kind enums.
 */
export enum PermissionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    PermissionMicrophone = 0,
    PermissionCamera = 1,
    PermissionGeolocation = 2,
    PermissionNotifications = 3,
    PermissionClipboardRead = 4,
};

export interface RGBA {
    "Red": number;
    "Green": number;
    "Blue": number;
    "Alpha": number;
}

export interface Rect {
    "X": number;
    "Y": number;
    "Width": number;
    "Height": number;
}

export interface Screen {
    /**
     * A unique identifier for the display
     */
    "ID": string;

    /**
     * The name of the display
     */
    "Name": string;

    /**
     * The scale factor of the display (DPI/96)
     */
    "ScaleFactor": number;

    /**
     * The x-coordinate of the top-left corner of the rectangle
     */
    "X": number;

    /**
     * The y-coordinate of the top-left corner of the rectangle
     */
    "Y": number;

    /**
     * The size of the display
     */
    "Size": Size;

    /**
     * The bounds of the display
     */
    "Bounds": Rect;

    /**
     * The physical bounds of the display (before scaling)
     */
    "PhysicalBounds": Rect;

    /**
     * The work area of the display
     */
    "WorkArea": Rect;

    /**
     * The physical work area of the display (before scaling)
     */
    "PhysicalWorkArea": Rect;

    /**
     * Whether this is the primary display
     */
    "IsPrimary": boolean;

    /**
     * The rotation of the display
     */
    "Rotation": number;
}

export interface ScreenManager {
}

export interface Size {
    "Width": number;
    "Height": number;
}

/**
 * SystemTrayManager manages system tray-related operations
 */
export interface SystemTrayManager {
}

export interface TextTheme {
    /**
     * Text is the colour of the text
     */
    "Text": number | null;

    /**
     * Background is the background colour of the text
     */
    "Background": number | null;
}

export enum Theme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * SystemDefault will use whatever the system theme is. The application will follow system theme changes.
     */
    SystemDefault = 0,

    /**
     * Dark Mode
     */
    Dark = 1,

    /**
     * Light Mode
     */
    Light = 2,
};

/**
 * ThemeSettings defines custom colours to use in dark or light mode.
 * They may be set using the hex values: 0x00BBGGRR
 */
export interface ThemeSettings {
    /**
     * Dark mode active window
     */
    "DarkModeActive": WindowTheme | null;

    /**
     * Dark mode inactive window
     */
    "DarkModeInactive": WindowTheme | null;

    /**
     * Light mode active window
     */
    "LightModeActive": WindowTheme | null;

    /**
     * Light mode inactive window
     */
    "LightModeInactive": WindowTheme | null;

    /**
     * Dark mode MenuBar
     */
    "DarkModeMenuBar": MenuBarTheme | null;

    /**
     * Light mode MenuBar
     */
    "LightModeMenuBar": MenuBarTheme | null;
}

/**
 * WebviewGpuPolicy values used for determining the webview's hardware acceleration policy.
 */
export enum WebviewGpuPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * WebviewGpuPolicyAlways Hardware acceleration is always enabled.
     */
    WebviewGpuPolicyAlways = 0,

    /**
     * WebviewGpuPolicyOnDemand Hardware acceleration is enabled/disabled as request by web contents.
     */
    WebviewGpuPolicyOnDemand = 1,

    /**
     * WebviewGpuPolicyNever Hardware acceleration is always disabled.
     */
    WebviewGpuPolicyNever = 2,
};

export interface WebviewWindowOptions {
    /**
     * Name is a unique identifier that can be given to a window.
     */
    "Name": string;

    /**
     * Title is the title of the window.
     */
    "Title": string;

    /**
     * Width is the starting width of the window.
     */
    "Width": number;

    /**
     * Height is the starting height of the window.
     */
    "Height": number;

    /**
     * AlwaysOnTop will make the window float above other windows.
     */
    "AlwaysOnTop": boolean;

    /**
     * URL is the URL to load in the window.
     */
    "URL": string;

    /**
     * DisableResize will disable the ability to resize the window.
     */
    "DisableResize": boolean;

    /**
     * Frameless will remove the window frame.
     */
    "Frameless": boolean;

    /**
     * MinWidth is the minimum width of the window.
     */
    "MinWidth": number;

    /**
     * MinHeight is the minimum height of the window.
     */
    "MinHeight": number;

    /**
     * MaxWidth is the maximum width of the window.
     */
    "MaxWidth": number;

    /**
     * MaxHeight is the maximum height of the window.
     */
    "MaxHeight": number;

    /**
     * StartState indicates the state of the window when it is first shown.
     * Default: WindowStateNormal
     */
    "StartState": WindowState;

    /**
     * BackgroundType is the type of background to use for the window.
     * Default: BackgroundTypeSolid
     */
    "BackgroundType": BackgroundType;

    /**
     * BackgroundColour is the colour to use for the window background.
     */
    "BackgroundColour": RGBA;

    /**
     * HTML is the HTML to load in the window.
     */
    "HTML": string;

    /**
     * AllowSimpleEventEmit gates the `wails:event:emit:<name>` postMessage
     * shortcut for this window. When true, JavaScript running in this
     * window can fire bare-named Wails custom events on the host bus via
     * `window._wails.invoke("wails:event:emit:<name>")`. The shortcut
     * exists so InitialHTML pages (loaded with no asset-server origin —
     * the framework's built-in updater window is the canonical case) can
     * still talk to the Go side without depending on the modern HTTP
     * runtime that requires `fetch("/wails/runtime")` to work.
     * 
     * SECURITY: leave this off (the default) unless you control every byte
     * of HTML that this window will ever load. When enabled, ANY script
     * running in the page — including content from a remote URL or any
     * XSS sink in user-supplied content — can synthesise Wails custom
     * events. The shortcut conveys bare names only (no payload) and
     * cannot reach the binding/Call path, but it CAN trigger any
     * `app.Event.On(name, ...)` handler your application code registers.
     * If you have a handler that performs a privileged action based on
     * the event name alone, that handler is exposed to anyone with
     * scripting access to this window.
     * 
     * Use [WebviewWindow.AsUpdaterWindow] in concert with
     * updater.BYOWindow to opt in cleanly when you're writing your own
     * updater UI; otherwise leave this false.
     */
    "AllowSimpleEventEmit": boolean;

    /**
     * JS is the JavaScript to load in the window.
     */
    "JS": string;

    /**
     * CSS is the CSS to load in the window.
     */
    "CSS": string;

    /**
     * Initial Position
     */
    "InitialPosition": WindowStartPosition;

    /**
     * X is the starting X position of the window.
     */
    "X": number;

    /**
     * Y is the starting Y position of the window.
     */
    "Y": number;

    /**
     * Screen specifies the target screen for initial window placement.
     * When set with WindowCentered, the window is centered on that screen's WorkArea.
     * When set with WindowXY, X/Y are treated as relative to that screen's WorkArea origin.
     * When nil, OS default behavior is used.
     */
    "Screen": Screen | null;

    /**
     * Hidden will hide the window when it is first created.
     */
    "Hidden": boolean;

    /**
     * Zoom is the zoom level of the window.
     */
    "Zoom": number;

    /**
     * ZoomControlEnabled will enable the zoom control.
     */
    "ZoomControlEnabled": boolean;

    /**
     * EnableFileDrop enables drag and drop of files onto the window.
     * When enabled, files dragged from the OS onto elements with the
     * `data-file-drop-target` attribute will trigger a FilesDropped event.
     */
    "EnableFileDrop": boolean;

    /**
     * Permissions controls how capability requests (camera, microphone, …)
     * from the web content are handled, per PermissionType. Unset entries use
     * PermissionDefault. Cross-platform; see the Permission constants for the
     * per-platform meaning of the default.
     */
    "Permissions": { [_ in PermissionType]?: Permission } | null;

    /**
     * OpenInspectorOnStartup will open the inspector when the window is first shown.
     */
    "OpenInspectorOnStartup": boolean;

    /**
     * Mac options
     */
    "Mac": MacWindow;

    /**
     * Windows options
     */
    "Windows": WindowsWindow;

    /**
     * Linux options
     */
    "Linux": LinuxWindow;

    /**
     * Toolbar button states
     */
    "MinimiseButtonState": ButtonState;
    "MaximiseButtonState": ButtonState;
    "CloseButtonState": ButtonState;

    /**
     * FullscreenButtonState controls the fullscreen button state.
     * On macOS this targets NSWindowZoomButton (the same green button as MaximiseButtonState);
     * the more restrictive of the two states is applied. On other platforms this is a no-op.
     */
    "FullscreenButtonState": ButtonState;

    /**
     * If true, the window's devtools will be available (default true in builds without the `production` build tag)
     */
    "DevToolsEnabled": boolean;

    /**
     * If true, the window's default context menu will be disabled (default false)
     */
    "DefaultContextMenuDisabled": boolean;

    /**
     * KeyBindings is a map of key bindings to functions
     */
    "KeyBindings": { [_ in string]?: any } | null;

    /**
     * IgnoreMouseEvents will ignore mouse events in the window (Windows + Mac only)
     */
    "IgnoreMouseEvents": boolean;

    /**
     * ContentProtectionEnabled specifies whether content protection is enabled, preventing screen capture and recording.
     * Effective on Windows and macOS only; no-op on Linux.
     * Best-effort protection with platform-specific caveats (see docs).
     */
    "ContentProtectionEnabled": boolean;

    /**
     * HideOnFocusLost will hide the window when it loses focus.
     * Useful for popup/transient windows like systray attached windows.
     * On Linux with focus-follows-mouse WMs (Hyprland, Sway, i3), this is automatically disabled
     * as it would cause the window to hide immediately when the mouse moves away.
     */
    "HideOnFocusLost": boolean;

    /**
     * HideOnEscape will hide the window when the Escape key is pressed.
     * Useful for popup/transient windows that should dismiss on Escape.
     */
    "HideOnEscape": boolean;

    /**
     * UseApplicationMenu indicates this window should use the application menu
     * set via app.Menu.Set() instead of requiring a window-specific menu.
     * On macOS this has no effect as the application menu is always global.
     * On Windows/Linux, if true and no explicit window menu is set, the window
     * will use the application menu. Defaults to false for backwards compatibility.
     */
    "UseApplicationMenu": boolean;
}

export type Window = any;

/**
 * WindowManager manages all window-related operations
 */
export interface WindowManager {
}

export enum WindowStartPosition {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    WindowCentered = 0,
    WindowXY = 1,
};

export enum WindowState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    WindowStateNormal = 0,
    WindowStateMinimised = 1,
    WindowStateMaximised = 2,
    WindowStateFullscreen = 3,
};

export interface WindowTheme {
    /**
     * BorderColour is the colour of the window border
     */
    "BorderColour": number | null;

    /**
     * TitleBarColour is the colour of the window title bar
     */
    "TitleBarColour": number | null;

    /**
     * TitleTextColour is the colour of the window title text
     */
    "TitleTextColour": number | null;
}

export interface WindowsWindow {
    /**
     * Select the type of translucent backdrop. Requires Windows 11 22621 or later.
     * Only used when window's `BackgroundType` is set to `BackgroundTypeTranslucent`.
     * Default: Auto
     */
    "BackdropType": BackdropType;

    /**
     * Disable the icon in the titlebar
     * Default: false
     */
    "DisableIcon": boolean;

    /**
     * Theme (Dark / Light / SystemDefault)
     * Default: SystemDefault - The application will follow system theme changes.
     */
    "Theme": Theme;

    /**
     * Specify custom colours to use for dark/light mode
     * Default: nil
     */
    "CustomTheme": ThemeSettings;

    /**
     * Disable all window decorations in Frameless mode, which means no "Aero Shadow" and no "Rounded Corner" will be shown.
     * "Rounded Corners" are only available on Windows 11.
     * Default: false
     */
    "DisableFramelessWindowDecorations": boolean;

    /**
     * WindowMask is used to set the window shape. Use a PNG with an alpha channel to create a custom shape.
     * Default: nil
     */
    "WindowMask": string | null;

    /**
     * WindowMaskDraggable is used to make the window draggable by clicking on the window mask.
     * Default: false
     */
    "WindowMaskDraggable": boolean;

    /**
     * WindowDidMoveDebounceMS is the amount of time to debounce the WindowDidMove event
     * when moving the window
     * Default: 0
     */
    "WindowDidMoveDebounceMS": number;

    /**
     * Event mapping for the window. This allows you to define a translation from one event to another.
     * Default: nil
     */
    "EventMapping": { [_ in events$0.WindowEventType]?: events$0.WindowEventType } | null;

    /**
     * HiddenOnTaskbar hides the window from the taskbar
     * Default: false
     */
    "HiddenOnTaskbar": boolean;

    /**
     * EnableSwipeGestures enables swipe gestures for the window
     * Default: false
     */
    "EnableSwipeGestures": boolean;

    /**
     * Menu is the menu to use for the window.
     */
    "Menu": Menu | null;

    /**
     * DisableMenu will disable the menu for the window.
     * Default: false
     */
    "DisableMenu": boolean;

    /**
     * Permissions map for WebView2. If empty, default permissions will be granted.
     */
    "Permissions": { [_ in CoreWebView2PermissionKind]?: CoreWebView2PermissionState } | null;

    /**
     * ExStyle is the extended window style
     */
    "ExStyle": number;

    /**
     * GeneralAutofillEnabled enables general autofill
     */
    "GeneralAutofillEnabled": boolean;

    /**
     * PasswordAutosaveEnabled enables autosaving passwords
     */
    "PasswordAutosaveEnabled": boolean;
}
