// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as optional$0 from "../../internal/optional/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../../log/slog/models.js";

export class App {
    /**
     * Creates a new App instance.
     * @param {Partial<App>} [$$source = {}] - The source object to create the App.
     */
    constructor($$source = {}) {
        if (!("Window" in $$source)) {
            /**
             * Manager pattern for organized API
             * @member
             * @type {WindowManager | null}
             */
            this["Window"] = null;
        }
        if (!("ContextMenu" in $$source)) {
            /**
             * @member
             * @type {ContextMenuManager | null}
             */
            this["ContextMenu"] = null;
        }
        if (!("KeyBinding" in $$source)) {
            /**
             * @member
             * @type {KeyBindingManager | null}
             */
            this["KeyBinding"] = null;
        }
        if (!("Browser" in $$source)) {
            /**
             * @member
             * @type {BrowserManager | null}
             */
            this["Browser"] = null;
        }
        if (!("Env" in $$source)) {
            /**
             * @member
             * @type {EnvironmentManager | null}
             */
            this["Env"] = null;
        }
        if (!("Dialog" in $$source)) {
            /**
             * @member
             * @type {DialogManager | null}
             */
            this["Dialog"] = null;
        }
        if (!("Event" in $$source)) {
            /**
             * @member
             * @type {EventManager | null}
             */
            this["Event"] = null;
        }
        if (!("Menu" in $$source)) {
            /**
             * @member
             * @type {MenuManager | null}
             */
            this["Menu"] = null;
        }
        if (!("Screen" in $$source)) {
            /**
             * @member
             * @type {ScreenManager | null}
             */
            this["Screen"] = null;
        }
        if (!("Clipboard" in $$source)) {
            /**
             * @member
             * @type {ClipboardManager | null}
             */
            this["Clipboard"] = null;
        }
        if (!("SystemTray" in $$source)) {
            /**
             * @member
             * @type {SystemTrayManager | null}
             */
            this["SystemTray"] = null;
        }
        if (!("Autostart" in $$source)) {
            /**
             * @member
             * @type {AutostartManager | null}
             */
            this["Autostart"] = null;
        }
        if (!("GlobalShortcut" in $$source)) {
            /**
             * @member
             * @type {GlobalShortcutManager | null}
             */
            this["GlobalShortcut"] = null;
        }
        if (!("Updater" in $$source)) {
            /**
             * @member
             * @type {updater$0.Updater | null}
             */
            this["Updater"] = null;
        }
        if (!("Logger" in $$source)) {
            /**
             * @member
             * @type {slog$0.Logger | null}
             */
            this["Logger"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {App}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType15;
        const $$createField8_0 = $$createType17;
        const $$createField9_0 = $$createType19;
        const $$createField10_0 = $$createType21;
        const $$createField11_0 = $$createType23;
        const $$createField12_0 = $$createType25;
        const $$createField13_0 = $$createType27;
        const $$createField14_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Window" in $$parsedSource) {
            $$parsedSource["Window"] = $$createField0_0($$parsedSource["Window"]);
        }
        if ("ContextMenu" in $$parsedSource) {
            $$parsedSource["ContextMenu"] = $$createField1_0($$parsedSource["ContextMenu"]);
        }
        if ("KeyBinding" in $$parsedSource) {
            $$parsedSource["KeyBinding"] = $$createField2_0($$parsedSource["KeyBinding"]);
        }
        if ("Browser" in $$parsedSource) {
            $$parsedSource["Browser"] = $$createField3_0($$parsedSource["Browser"]);
        }
        if ("Env" in $$parsedSource) {
            $$parsedSource["Env"] = $$createField4_0($$parsedSource["Env"]);
        }
        if ("Dialog" in $$parsedSource) {
            $$parsedSource["Dialog"] = $$createField5_0($$parsedSource["Dialog"]);
        }
        if ("Event" in $$parsedSource) {
            $$parsedSource["Event"] = $$createField6_0($$parsedSource["Event"]);
        }
        if ("Menu" in $$parsedSource) {
            $$parsedSource["Menu"] = $$createField7_0($$parsedSource["Menu"]);
        }
        if ("Screen" in $$parsedSource) {
            $$parsedSource["Screen"] = $$createField8_0($$parsedSource["Screen"]);
        }
        if ("Clipboard" in $$parsedSource) {
            $$parsedSource["Clipboard"] = $$createField9_0($$parsedSource["Clipboard"]);
        }
        if ("SystemTray" in $$parsedSource) {
            $$parsedSource["SystemTray"] = $$createField10_0($$parsedSource["SystemTray"]);
        }
        if ("Autostart" in $$parsedSource) {
            $$parsedSource["Autostart"] = $$createField11_0($$parsedSource["Autostart"]);
        }
        if ("GlobalShortcut" in $$parsedSource) {
            $$parsedSource["GlobalShortcut"] = $$createField12_0($$parsedSource["GlobalShortcut"]);
        }
        if ("Updater" in $$parsedSource) {
            $$parsedSource["Updater"] = $$createField13_0($$parsedSource["Updater"]);
        }
        if ("Logger" in $$parsedSource) {
            $$parsedSource["Logger"] = $$createField14_0($$parsedSource["Logger"]);
        }
        return new App(/** @type {Partial<App>} */($$parsedSource));
    }
}

/**
 * AutostartManager provides cross-platform control over whether the
 * application launches when the user logs in.
 * 
 * Registration takes effect on the next login, not immediately.
 * 
 * Platform behaviour:
 * 
 *   - macOS 13+ (bundled .app):  SMAppService.mainAppService — works for
 *     sandboxed and Mac-App-Store apps, no TCC automation prompt.
 *   - macOS (older or unbundled): a LaunchAgent plist is written to
 *     ~/Library/LaunchAgents/.
 *   - Windows: a value is added under
 *     HKCU\Software\Microsoft\Windows\CurrentVersion\Run.
 *   - Linux: an .desktop file is written to $XDG_CONFIG_HOME/autostart/
 *     (defaulting to ~/.config/autostart/).
 *   - Android / iOS / server builds: ErrAutostartNotSupported.
 */
export class AutostartManager {
    /**
     * Creates a new AutostartManager instance.
     * @param {Partial<AutostartManager>} [$$source = {}] - The source object to create the AutostartManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutostartManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutostartManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutostartManager(/** @type {Partial<AutostartManager>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const BackdropType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Auto: 0,
    None: 1,
    Mica: 2,
    Acrylic: 3,
    Tabbed: 4,
};

/**
 * @readonly
 * @enum {number}
 */
export const BackgroundType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    BackgroundTypeSolid: 0,
    BackgroundTypeTransparent: 1,
    BackgroundTypeTranslucent: 2,
};

/**
 * BrowserManager manages browser-related operations
 */
export class BrowserManager {
    /**
     * Creates a new BrowserManager instance.
     * @param {Partial<BrowserManager>} [$$source = {}] - The source object to create the BrowserManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BrowserManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserManager(/** @type {Partial<BrowserManager>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const ButtonState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    ButtonEnabled: 0,
    ButtonDisabled: 1,
    ButtonHidden: 2,
};

/**
 * ClipboardManager manages clipboard operations
 */
export class ClipboardManager {
    /**
     * Creates a new ClipboardManager instance.
     * @param {Partial<ClipboardManager>} [$$source = {}] - The source object to create the ClipboardManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClipboardManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardManager(/** @type {Partial<ClipboardManager>} */($$parsedSource));
    }
}

/**
 * ContextMenuManager manages all context menu operations
 */
export class ContextMenuManager {
    /**
     * Creates a new ContextMenuManager instance.
     * @param {Partial<ContextMenuManager>} [$$source = {}] - The source object to create the ContextMenuManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextMenuManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextMenuManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextMenuManager(/** @type {Partial<ContextMenuManager>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const CoreWebView2PermissionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CoreWebView2PermissionKindUnknownPermission: 0,
    CoreWebView2PermissionKindMicrophone: 1,
    CoreWebView2PermissionKindCamera: 2,
    CoreWebView2PermissionKindGeolocation: 3,
    CoreWebView2PermissionKindNotifications: 4,
    CoreWebView2PermissionKindOtherSensors: 5,
    CoreWebView2PermissionKindClipboardRead: 6,
};

/**
 * @readonly
 * @enum {number}
 */
export const CoreWebView2PermissionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CoreWebView2PermissionStateDefault: 0,
    CoreWebView2PermissionStateAllow: 1,
    CoreWebView2PermissionStateDeny: 2,
};

/**
 * DialogManager manages dialog-related operations
 */
export class DialogManager {
    /**
     * Creates a new DialogManager instance.
     * @param {Partial<DialogManager>} [$$source = {}] - The source object to create the DialogManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DialogManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DialogManager(/** @type {Partial<DialogManager>} */($$parsedSource));
    }
}

/**
 * EnvironmentManager manages environment-related operations
 */
export class EnvironmentManager {
    /**
     * Creates a new EnvironmentManager instance.
     * @param {Partial<EnvironmentManager>} [$$source = {}] - The source object to create the EnvironmentManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentManager(/** @type {Partial<EnvironmentManager>} */($$parsedSource));
    }
}

/**
 * EventManager manages event-related operations
 */
export class EventManager {
    /**
     * Creates a new EventManager instance.
     * @param {Partial<EventManager>} [$$source = {}] - The source object to create the EventManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventManager(/** @type {Partial<EventManager>} */($$parsedSource));
    }
}

/**
 * GlobalShortcutManager manages application-wide (global) keyboard shortcuts.
 * 
 * Unlike menu accelerators or [KeyBindingManager] - which only fire while a
 * Wails window has focus - a global shortcut fires regardless of which
 * application is currently focused, as long as the Wails application is
 * running.
 * 
 * Global shortcuts are owned by the application, not by an individual window.
 * Registering the same accelerator twice within the same application is
 * reported as an error and the original binding is preserved; see [Register].
 * 
 * Shortcuts may be registered before [App.Run] is called: the binding with the
 * operating system is then deferred until the application starts.
 */
export class GlobalShortcutManager {
    /**
     * Creates a new GlobalShortcutManager instance.
     * @param {Partial<GlobalShortcutManager>} [$$source = {}] - The source object to create the GlobalShortcutManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalShortcutManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlobalShortcutManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobalShortcutManager(/** @type {Partial<GlobalShortcutManager>} */($$parsedSource));
    }
}

/**
 * KeyBindingManager manages all key binding operations
 */
export class KeyBindingManager {
    /**
     * Creates a new KeyBindingManager instance.
     * @param {Partial<KeyBindingManager>} [$$source = {}] - The source object to create the KeyBindingManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyBindingManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyBindingManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyBindingManager(/** @type {Partial<KeyBindingManager>} */($$parsedSource));
    }
}

/**
 * LinuxMenuStyle defines how the application menu is displayed on Linux (GTK4 only).
 * On GTK3 builds, this option is ignored and MenuBar style is always used.
 * @readonly
 * @enum {number}
 */
export const LinuxMenuStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * LinuxMenuStyleMenuBar displays a traditional menu bar below the title bar (default)
     */
    LinuxMenuStyleMenuBar: 0,

    /**
     * LinuxMenuStylePrimaryMenu displays a primary menu button in the header bar (GNOME style)
     */
    LinuxMenuStylePrimaryMenu: 1,
};

/**
 * LinuxWindow specific to Linux windows
 */
export class LinuxWindow {
    /**
     * Creates a new LinuxWindow instance.
     * @param {Partial<LinuxWindow>} [$$source = {}] - The source object to create the LinuxWindow.
     */
    constructor($$source = {}) {
        if (!("Icon" in $$source)) {
            /**
             * Icon Sets up the icon representing the window. This icon is used when the window is minimized
             * (also known as iconified).
             * @member
             * @type {string}
             */
            this["Icon"] = "";
        }
        if (!("WindowIsTranslucent" in $$source)) {
            /**
             * WindowIsTranslucent sets the window's background to transparent when enabled.
             * @member
             * @type {boolean}
             */
            this["WindowIsTranslucent"] = false;
        }
        if (!("WebviewGpuPolicy" in $$source)) {
            /**
             * WebviewGpuPolicy used for determining the hardware acceleration policy for the webview.
             *   - WebviewGpuPolicyAlways
             *   - WebviewGpuPolicyOnDemand
             *   - WebviewGpuPolicyNever
             * 
             * Due to https://github.com/wailsapp/wails/issues/2977, if options.Linux is nil
             * in the call to wails.Run(), WebviewGpuPolicy is set by default to WebviewGpuPolicyNever.
             * Client code may override this behavior by passing a non-nil Options and set
             * WebviewGpuPolicy as needed.
             * @member
             * @type {WebviewGpuPolicy}
             */
            this["WebviewGpuPolicy"] = WebviewGpuPolicy.$zero;
        }
        if (!("WindowDidMoveDebounceMS" in $$source)) {
            /**
             * WindowDidMoveDebounceMS is the debounce time in milliseconds for the WindowDidMove event
             * @member
             * @type {number}
             */
            this["WindowDidMoveDebounceMS"] = 0;
        }
        if (!("Menu" in $$source)) {
            /**
             * Menu is the window's menu
             * @member
             * @type {Menu | null}
             */
            this["Menu"] = null;
        }
        if (!("MenuStyle" in $$source)) {
            /**
             * MenuStyle controls how the menu is displayed (GTK4 only, ignored on GTK3)
             * @member
             * @type {LinuxMenuStyle}
             */
            this["MenuStyle"] = LinuxMenuStyle.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinuxWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinuxWindow}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField4_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Icon" in $$parsedSource) {
            $$parsedSource["Icon"] = $$createField0_0($$parsedSource["Icon"]);
        }
        if ("Menu" in $$parsedSource) {
            $$parsedSource["Menu"] = $$createField4_0($$parsedSource["Menu"]);
        }
        return new LinuxWindow(/** @type {Partial<LinuxWindow>} */($$parsedSource));
    }
}

/**
 * MacAppearanceType is a type of Appearance for Cocoa windows
 * @readonly
 * @enum {string}
 */
export const MacAppearanceType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * DefaultAppearance uses the default system value
     */
    DefaultAppearance: "",

    /**
     * NSAppearanceNameAqua - The standard light system appearance.
     */
    NSAppearanceNameAqua: "NSAppearanceNameAqua",

    /**
     * NSAppearanceNameDarkAqua - The standard dark system appearance.
     */
    NSAppearanceNameDarkAqua: "NSAppearanceNameDarkAqua",

    /**
     * NSAppearanceNameVibrantLight - The light vibrant appearance
     */
    NSAppearanceNameVibrantLight: "NSAppearanceNameVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastAqua - A high-contrast version of the standard light system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastAqua: "NSAppearanceNameAccessibilityHighContrastAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastDarkAqua - A high-contrast version of the standard dark system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastDarkAqua: "NSAppearanceNameAccessibilityHighContrastDarkAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantLight - A high-contrast version of the light vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantLight: "NSAppearanceNameAccessibilityHighContrastVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantDark - A high-contrast version of the dark vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantDark: "NSAppearanceNameAccessibilityHighContrastVibrantDark",
};

/**
 * MacBackdrop is the backdrop type for macOS
 * @readonly
 * @enum {number}
 */
export const MacBackdrop = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacBackdropNormal - The default value. The window will have a normal opaque background.
     */
    MacBackdropNormal: 0,

    /**
     * MacBackdropTransparent - The window will have a transparent background, with the content underneath it being visible
     */
    MacBackdropTransparent: 1,

    /**
     * MacBackdropTranslucent - The window will have a translucent background, with the content underneath it being "fuzzy" or "frosted"
     */
    MacBackdropTranslucent: 2,

    /**
     * MacBackdropLiquidGlass - The window will use Apple's Liquid Glass effect (macOS 15.0+ with fallback to translucent)
     */
    MacBackdropLiquidGlass: 3,
};

/**
 * MacLiquidGlass contains configuration for the Liquid Glass effect
 */
export class MacLiquidGlass {
    /**
     * Creates a new MacLiquidGlass instance.
     * @param {Partial<MacLiquidGlass>} [$$source = {}] - The source object to create the MacLiquidGlass.
     */
    constructor($$source = {}) {
        if (!("Style" in $$source)) {
            /**
             * Style of the glass effect
             * @member
             * @type {MacLiquidGlassStyle}
             */
            this["Style"] = MacLiquidGlassStyle.$zero;
        }
        if (!("Material" in $$source)) {
            /**
             * Material to use for NSVisualEffectView (when NSGlassEffectView is not available)
             * Set to NSVisualEffectMaterialAuto to use automatic selection based on Style
             * @member
             * @type {NSVisualEffectMaterial}
             */
            this["Material"] = NSVisualEffectMaterial.$zero;
        }
        if (!("CornerRadius" in $$source)) {
            /**
             * Corner radius for the glass effect (0 for square corners)
             * @member
             * @type {number}
             */
            this["CornerRadius"] = 0;
        }
        if (!("TintColor" in $$source)) {
            /**
             * Tint color for the glass (optional, nil for no tint)
             * @member
             * @type {RGBA | null}
             */
            this["TintColor"] = null;
        }
        if (!("GroupID" in $$source)) {
            /**
             * Group identifier for merging multiple glass windows
             * @member
             * @type {string}
             */
            this["GroupID"] = "";
        }
        if (!("GroupSpacing" in $$source)) {
            /**
             * Spacing between grouped glass elements (in points)
             * @member
             * @type {number}
             */
            this["GroupSpacing"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacLiquidGlass instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacLiquidGlass}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TintColor" in $$parsedSource) {
            $$parsedSource["TintColor"] = $$createField3_0($$parsedSource["TintColor"]);
        }
        return new MacLiquidGlass(/** @type {Partial<MacLiquidGlass>} */($$parsedSource));
    }
}

/**
 * MacLiquidGlassStyle defines the style of the Liquid Glass effect
 * @readonly
 * @enum {number}
 */
export const MacLiquidGlassStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * LiquidGlassStyleAutomatic - System determines the best style
     */
    LiquidGlassStyleAutomatic: 0,

    /**
     * LiquidGlassStyleLight - Light glass appearance
     */
    LiquidGlassStyleLight: 1,

    /**
     * LiquidGlassStyleDark - Dark glass appearance
     */
    LiquidGlassStyleDark: 2,

    /**
     * LiquidGlassStyleVibrant - Vibrant glass with enhanced effects
     */
    LiquidGlassStyleVibrant: 3,
};

/**
 * MacTitleBar contains options for the Mac titlebar
 */
export class MacTitleBar {
    /**
     * Creates a new MacTitleBar instance.
     * @param {Partial<MacTitleBar>} [$$source = {}] - The source object to create the MacTitleBar.
     */
    constructor($$source = {}) {
        if (!("AppearsTransparent" in $$source)) {
            /**
             * AppearsTransparent will make the titlebar transparent
             * @member
             * @type {boolean}
             */
            this["AppearsTransparent"] = false;
        }
        if (!("Hide" in $$source)) {
            /**
             * Hide will hide the titlebar
             * @member
             * @type {boolean}
             */
            this["Hide"] = false;
        }
        if (!("HideTitle" in $$source)) {
            /**
             * HideTitle will hide the title
             * @member
             * @type {boolean}
             */
            this["HideTitle"] = false;
        }
        if (!("FullSizeContent" in $$source)) {
            /**
             * FullSizeContent will extend the window content to the full size of the window
             * @member
             * @type {boolean}
             */
            this["FullSizeContent"] = false;
        }
        if (!("UseToolbar" in $$source)) {
            /**
             * UseToolbar will use a toolbar instead of a titlebar
             * @member
             * @type {boolean}
             */
            this["UseToolbar"] = false;
        }
        if (!("HideToolbarSeparator" in $$source)) {
            /**
             * HideToolbarSeparator will hide the toolbar separator
             * @member
             * @type {boolean}
             */
            this["HideToolbarSeparator"] = false;
        }
        if (!("ShowToolbarWhenFullscreen" in $$source)) {
            /**
             * ShowToolbarWhenFullscreen will keep the toolbar visible when the window is in fullscreen mode
             * @member
             * @type {boolean}
             */
            this["ShowToolbarWhenFullscreen"] = false;
        }
        if (!("ToolbarStyle" in $$source)) {
            /**
             * ToolbarStyle is the style of toolbar to use
             * @member
             * @type {MacToolbarStyle}
             */
            this["ToolbarStyle"] = MacToolbarStyle.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacTitleBar instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacTitleBar}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacTitleBar(/** @type {Partial<MacTitleBar>} */($$parsedSource));
    }
}

/**
 * MacToolbarStyle is the style of toolbar for macOS
 * @readonly
 * @enum {number}
 */
export const MacToolbarStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacToolbarStyleAutomatic - The default value. The style will be determined by the window's given configuration
     */
    MacToolbarStyleAutomatic: 0,

    /**
     * MacToolbarStyleExpanded - The toolbar will appear below the window title
     */
    MacToolbarStyleExpanded: 1,

    /**
     * MacToolbarStylePreference - The toolbar will appear below the window title and the items in the toolbar will attempt to have equal widths when possible
     */
    MacToolbarStylePreference: 2,

    /**
     * MacToolbarStyleUnified - The window title will appear inline with the toolbar when visible
     */
    MacToolbarStyleUnified: 3,

    /**
     * MacToolbarStyleUnifiedCompact - Same as MacToolbarStyleUnified, but with reduced margins in the toolbar allowing more focus to be on the contents of the window
     */
    MacToolbarStyleUnifiedCompact: 4,
};

/**
 * MacWebviewPreferences contains preferences for the Mac webview
 */
export class MacWebviewPreferences {
    /**
     * Creates a new MacWebviewPreferences instance.
     * @param {Partial<MacWebviewPreferences>} [$$source = {}] - The source object to create the MacWebviewPreferences.
     */
    constructor($$source = {}) {
        if (!("TabFocusesLinks" in $$source)) {
            /**
             * TabFocusesLinks will enable tabbing to links
             * @member
             * @type {optional$0.Bool}
             */
            this["TabFocusesLinks"] = (new optional$0.Bool());
        }
        if (!("TextInteractionEnabled" in $$source)) {
            /**
             * TextInteractionEnabled will enable text interaction
             * @member
             * @type {optional$0.Bool}
             */
            this["TextInteractionEnabled"] = (new optional$0.Bool());
        }
        if (!("FullscreenEnabled" in $$source)) {
            /**
             * FullscreenEnabled will enable fullscreen
             * @member
             * @type {optional$0.Bool}
             */
            this["FullscreenEnabled"] = (new optional$0.Bool());
        }
        if (!("AllowsBackForwardNavigationGestures" in $$source)) {
            /**
             * AllowsBackForwardNavigationGestures enables horizontal swipe gestures for back/forward navigation
             * @member
             * @type {optional$0.Bool}
             */
            this["AllowsBackForwardNavigationGestures"] = (new optional$0.Bool());
        }
        if (!("AllowsMagnification" in $$source)) {
            /**
             * AllowsMagnification enables pinch-to-zoom on the webview
             * @member
             * @type {optional$0.Bool}
             */
            this["AllowsMagnification"] = (new optional$0.Bool());
        }
        if (!("AllowsAirPlayForMediaPlayback" in $$source)) {
            /**
             * AllowsAirPlayForMediaPlayback enables AirPlay media playback
             * @member
             * @type {optional$0.Bool}
             */
            this["AllowsAirPlayForMediaPlayback"] = (new optional$0.Bool());
        }
        if (!("JavaScriptCanOpenWindowsAutomatically" in $$source)) {
            /**
             * JavaScriptCanOpenWindowsAutomatically allows JS to open windows without a user gesture
             * @member
             * @type {optional$0.Bool}
             */
            this["JavaScriptCanOpenWindowsAutomatically"] = (new optional$0.Bool());
        }
        if (!("MinimumFontSize" in $$source)) {
            /**
             * MinimumFontSize sets the minimum font size in points
             * @member
             * @type {optional$0.Var<number>}
             */
            this["MinimumFontSize"] = (new optional$0.Var());
        }
        if (!("ApplicationNameForUserAgent" in $$source)) {
            /**
             * ApplicationNameForUserAgent overrides the application name portion of the user agent string.
             * Leave empty to use the default "wails.io" suffix.
             * @member
             * @type {string}
             */
            this["ApplicationNameForUserAgent"] = "";
        }
        if (!("EnableAutoplayWithoutUserAction" in $$source)) {
            /**
             * EnableAutoplayWithoutUserAction allows media to start playing automatically
             * without requiring a user gesture. Maps to WKWebViewConfiguration.mediaTypesRequiringUserActionForPlayback.
             * @member
             * @type {optional$0.Bool}
             */
            this["EnableAutoplayWithoutUserAction"] = (new optional$0.Bool());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacWebviewPreferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacWebviewPreferences}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType34;
        const $$createField1_0 = $$createType34;
        const $$createField2_0 = $$createType34;
        const $$createField3_0 = $$createType34;
        const $$createField4_0 = $$createType34;
        const $$createField5_0 = $$createType34;
        const $$createField6_0 = $$createType34;
        const $$createField7_0 = $$createType35;
        const $$createField9_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TabFocusesLinks" in $$parsedSource) {
            $$parsedSource["TabFocusesLinks"] = $$createField0_0($$parsedSource["TabFocusesLinks"]);
        }
        if ("TextInteractionEnabled" in $$parsedSource) {
            $$parsedSource["TextInteractionEnabled"] = $$createField1_0($$parsedSource["TextInteractionEnabled"]);
        }
        if ("FullscreenEnabled" in $$parsedSource) {
            $$parsedSource["FullscreenEnabled"] = $$createField2_0($$parsedSource["FullscreenEnabled"]);
        }
        if ("AllowsBackForwardNavigationGestures" in $$parsedSource) {
            $$parsedSource["AllowsBackForwardNavigationGestures"] = $$createField3_0($$parsedSource["AllowsBackForwardNavigationGestures"]);
        }
        if ("AllowsMagnification" in $$parsedSource) {
            $$parsedSource["AllowsMagnification"] = $$createField4_0($$parsedSource["AllowsMagnification"]);
        }
        if ("AllowsAirPlayForMediaPlayback" in $$parsedSource) {
            $$parsedSource["AllowsAirPlayForMediaPlayback"] = $$createField5_0($$parsedSource["AllowsAirPlayForMediaPlayback"]);
        }
        if ("JavaScriptCanOpenWindowsAutomatically" in $$parsedSource) {
            $$parsedSource["JavaScriptCanOpenWindowsAutomatically"] = $$createField6_0($$parsedSource["JavaScriptCanOpenWindowsAutomatically"]);
        }
        if ("MinimumFontSize" in $$parsedSource) {
            $$parsedSource["MinimumFontSize"] = $$createField7_0($$parsedSource["MinimumFontSize"]);
        }
        if ("EnableAutoplayWithoutUserAction" in $$parsedSource) {
            $$parsedSource["EnableAutoplayWithoutUserAction"] = $$createField9_0($$parsedSource["EnableAutoplayWithoutUserAction"]);
        }
        return new MacWebviewPreferences(/** @type {Partial<MacWebviewPreferences>} */($$parsedSource));
    }
}

/**
 * MacWindow contains macOS specific options for Webview Windows
 */
export class MacWindow {
    /**
     * Creates a new MacWindow instance.
     * @param {Partial<MacWindow>} [$$source = {}] - The source object to create the MacWindow.
     */
    constructor($$source = {}) {
        if (!("Backdrop" in $$source)) {
            /**
             * Backdrop is the backdrop type for the window
             * @member
             * @type {MacBackdrop}
             */
            this["Backdrop"] = MacBackdrop.$zero;
        }
        if (!("DisableShadow" in $$source)) {
            /**
             * DisableShadow will disable the window shadow
             * @member
             * @type {boolean}
             */
            this["DisableShadow"] = false;
        }
        if (!("TitleBar" in $$source)) {
            /**
             * TitleBar contains options for the Mac titlebar
             * @member
             * @type {MacTitleBar}
             */
            this["TitleBar"] = (new MacTitleBar());
        }
        if (!("Appearance" in $$source)) {
            /**
             * Appearance is the appearance type for the window
             * @member
             * @type {MacAppearanceType}
             */
            this["Appearance"] = MacAppearanceType.$zero;
        }
        if (!("InvisibleTitleBarHeight" in $$source)) {
            /**
             * InvisibleTitleBarHeight defines the height of an invisible titlebar which responds to dragging
             * @member
             * @type {number}
             */
            this["InvisibleTitleBarHeight"] = 0;
        }
        if (!("EventMapping" in $$source)) {
            /**
             * Maps events from platform specific to common event types
             * @member
             * @type {{ [_ in events$0.WindowEventType]?: events$0.WindowEventType }}
             */
            this["EventMapping"] = {};
        }
        if (!("EnableFraudulentWebsiteWarnings" in $$source)) {
            /**
             * EnableFraudulentWebsiteWarnings will enable warnings for fraudulent websites.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["EnableFraudulentWebsiteWarnings"] = false;
        }
        if (!("WebviewPreferences" in $$source)) {
            /**
             * WebviewPreferences contains preferences for the webview
             * @member
             * @type {MacWebviewPreferences}
             */
            this["WebviewPreferences"] = (new MacWebviewPreferences());
        }
        if (!("WindowLevel" in $$source)) {
            /**
             * WindowLevel sets the window level to control the order of windows in the screen
             * @member
             * @type {MacWindowLevel}
             */
            this["WindowLevel"] = MacWindowLevel.$zero;
        }
        if (!("CollectionBehavior" in $$source)) {
            /**
             * CollectionBehavior controls how the window behaves across macOS Spaces and fullscreen
             * @member
             * @type {MacWindowCollectionBehavior}
             */
            this["CollectionBehavior"] = MacWindowCollectionBehavior.$zero;
        }
        if (!("TabbingMode" in $$source)) {
            /**
             * TabbingMode sets the window tabbing mode (macOS 10.12+)
             * @member
             * @type {MacWindowTabbingMode}
             */
            this["TabbingMode"] = MacWindowTabbingMode.$zero;
        }
        if (!("LiquidGlass" in $$source)) {
            /**
             * LiquidGlass contains configuration for the Liquid Glass effect
             * @member
             * @type {MacLiquidGlass}
             */
            this["LiquidGlass"] = (new MacLiquidGlass());
        }
        if (!("DisableEscapeExitsFullscreen" in $$source)) {
            /**
             * DisableEscapeExitsFullscreen prevents the Escape key from exiting fullscreen mode.
             * When true, Esc keypresses are swallowed while the window is fullscreen, allowing
             * web content (e.g. modals with Esc-to-close behaviour) to handle Esc directly.
             * Default false preserves standard macOS behaviour where Esc exits fullscreen.
             * @member
             * @type {boolean}
             */
            this["DisableEscapeExitsFullscreen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacWindow}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType36;
        const $$createField5_0 = $$createType37;
        const $$createField7_0 = $$createType38;
        const $$createField11_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TitleBar" in $$parsedSource) {
            $$parsedSource["TitleBar"] = $$createField2_0($$parsedSource["TitleBar"]);
        }
        if ("EventMapping" in $$parsedSource) {
            $$parsedSource["EventMapping"] = $$createField5_0($$parsedSource["EventMapping"]);
        }
        if ("WebviewPreferences" in $$parsedSource) {
            $$parsedSource["WebviewPreferences"] = $$createField7_0($$parsedSource["WebviewPreferences"]);
        }
        if ("LiquidGlass" in $$parsedSource) {
            $$parsedSource["LiquidGlass"] = $$createField11_0($$parsedSource["LiquidGlass"]);
        }
        return new MacWindow(/** @type {Partial<MacWindow>} */($$parsedSource));
    }
}

/**
 * MacWindowCollectionBehavior controls window behavior across macOS Spaces and fullscreen.
 * These correspond to NSWindowCollectionBehavior bitmask values and can be combined using bitwise OR.
 * For example: MacWindowCollectionBehaviorCanJoinAllSpaces | MacWindowCollectionBehaviorFullScreenAuxiliary
 * @readonly
 * @enum {number}
 */
export const MacWindowCollectionBehavior = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacWindowCollectionBehaviorDefault is zero value - when set, FullScreenPrimary is used for backwards compatibility
     */
    MacWindowCollectionBehaviorDefault: 0,

    /**
     * MacWindowCollectionBehaviorCanJoinAllSpaces allows window to appear on all Spaces
     * 1
     */
    MacWindowCollectionBehaviorCanJoinAllSpaces: 1,

    /**
     * MacWindowCollectionBehaviorMoveToActiveSpace moves window to active Space when shown
     * 2
     */
    MacWindowCollectionBehaviorMoveToActiveSpace: 2,

    /**
     * MacWindowCollectionBehaviorManaged is the default managed window behavior
     * 4
     */
    MacWindowCollectionBehaviorManaged: 4,

    /**
     * MacWindowCollectionBehaviorTransient marks window as temporary/transient
     * 8
     */
    MacWindowCollectionBehaviorTransient: 8,

    /**
     * MacWindowCollectionBehaviorStationary keeps window stationary during Space switches
     * 16
     */
    MacWindowCollectionBehaviorStationary: 16,

    /**
     * MacWindowCollectionBehaviorParticipatesInCycle includes window in Cmd+` cycling (default for normal windows)
     * 32
     */
    MacWindowCollectionBehaviorParticipatesInCycle: 32,

    /**
     * MacWindowCollectionBehaviorIgnoresCycle excludes window from Cmd+` cycling
     * 64
     */
    MacWindowCollectionBehaviorIgnoresCycle: 64,

    /**
     * MacWindowCollectionBehaviorFullScreenPrimary allows the window to enter fullscreen
     * 128
     */
    MacWindowCollectionBehaviorFullScreenPrimary: 128,

    /**
     * MacWindowCollectionBehaviorFullScreenAuxiliary allows window to overlay fullscreen apps
     * 256
     */
    MacWindowCollectionBehaviorFullScreenAuxiliary: 256,

    /**
     * MacWindowCollectionBehaviorFullScreenNone prevents window from entering fullscreen (macOS 10.7+)
     * 512
     */
    MacWindowCollectionBehaviorFullScreenNone: 512,

    /**
     * MacWindowCollectionBehaviorFullScreenAllowsTiling allows side-by-side tiling in fullscreen (macOS 10.11+)
     * 2048
     */
    MacWindowCollectionBehaviorFullScreenAllowsTiling: 2048,

    /**
     * MacWindowCollectionBehaviorFullScreenDisallowsTiling prevents tiling in fullscreen (macOS 10.11+)
     * 4096
     */
    MacWindowCollectionBehaviorFullScreenDisallowsTiling: 4096,
};

/**
 * @readonly
 * @enum {string}
 */
export const MacWindowLevel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MacWindowLevelNormal: "normal",
    MacWindowLevelFloating: "floating",
    MacWindowLevelTornOffMenu: "tornOffMenu",
    MacWindowLevelModalPanel: "modalPanel",
    MacWindowLevelMainMenu: "mainMenu",
    MacWindowLevelStatus: "status",
    MacWindowLevelPopUpMenu: "popUpMenu",
    MacWindowLevelScreenSaver: "screenSaver",
};

/**
 * MacWindowTabbingMode controls window tabbing behavior (macOS 10.12+).
 * Values map to NSWindowTabbingMode (offset by 1 so the zero value is an "unset" sentinel).
 * @readonly
 * @enum {number}
 */
export const MacWindowTabbingMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacWindowTabbingModeDefault is the zero-value sentinel meaning "not explicitly set".
     * At runtime it resolves to Disallowed.
     */
    MacWindowTabbingModeDefault: 0,

    /**
     * MacWindowTabbingModeAutomatic allows the system to determine tabbing behavior
     */
    MacWindowTabbingModeAutomatic: 1,

    /**
     * MacWindowTabbingModePreferred indicates the window prefers to be in tabbing mode
     */
    MacWindowTabbingModePreferred: 2,

    /**
     * MacWindowTabbingModeDisallowed prevents the window from being tabbed
     */
    MacWindowTabbingModeDisallowed: 3,
};

export class Menu {
    /**
     * Creates a new Menu instance.
     * @param {Partial<Menu>} [$$source = {}] - The source object to create the Menu.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Menu instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Menu}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Menu(/** @type {Partial<Menu>} */($$parsedSource));
    }
}

export class MenuBarTheme {
    /**
     * Creates a new MenuBarTheme instance.
     * @param {Partial<MenuBarTheme>} [$$source = {}] - The source object to create the MenuBarTheme.
     */
    constructor($$source = {}) {
        if (!("Default" in $$source)) {
            /**
             * Default is the default theme
             * @member
             * @type {TextTheme | null}
             */
            this["Default"] = null;
        }
        if (!("Hover" in $$source)) {
            /**
             * Hover defines the theme to use when the menu item is hovered
             * @member
             * @type {TextTheme | null}
             */
            this["Hover"] = null;
        }
        if (!("Selected" in $$source)) {
            /**
             * Selected defines the theme to use when the menu item is selected
             * @member
             * @type {TextTheme | null}
             */
            this["Selected"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuBarTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuBarTheme}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType41;
        const $$createField1_0 = $$createType41;
        const $$createField2_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Default" in $$parsedSource) {
            $$parsedSource["Default"] = $$createField0_0($$parsedSource["Default"]);
        }
        if ("Hover" in $$parsedSource) {
            $$parsedSource["Hover"] = $$createField1_0($$parsedSource["Hover"]);
        }
        if ("Selected" in $$parsedSource) {
            $$parsedSource["Selected"] = $$createField2_0($$parsedSource["Selected"]);
        }
        return new MenuBarTheme(/** @type {Partial<MenuBarTheme>} */($$parsedSource));
    }
}

/**
 * MenuManager manages menu-related operations
 */
export class MenuManager {
    /**
     * Creates a new MenuManager instance.
     * @param {Partial<MenuManager>} [$$source = {}] - The source object to create the MenuManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuManager(/** @type {Partial<MenuManager>} */($$parsedSource));
    }
}

/**
 * NSVisualEffectMaterial represents the NSVisualEffectMaterial enum for macOS
 * @readonly
 * @enum {number}
 */
export const NSVisualEffectMaterial = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * NSVisualEffectMaterial values from macOS SDK
     */
    NSVisualEffectMaterialAppearanceBased: 0,
    NSVisualEffectMaterialLight: 1,
    NSVisualEffectMaterialDark: 2,
    NSVisualEffectMaterialTitlebar: 3,
    NSVisualEffectMaterialSelection: 4,
    NSVisualEffectMaterialMenu: 5,
    NSVisualEffectMaterialPopover: 6,
    NSVisualEffectMaterialSidebar: 7,
    NSVisualEffectMaterialHeaderView: 10,
    NSVisualEffectMaterialSheet: 11,
    NSVisualEffectMaterialWindowBackground: 12,
    NSVisualEffectMaterialHUDWindow: 13,
    NSVisualEffectMaterialFullScreenUI: 15,
    NSVisualEffectMaterialToolTip: 17,
    NSVisualEffectMaterialContentBackground: 18,
    NSVisualEffectMaterialUnderWindowBackground: 21,
    NSVisualEffectMaterialUnderPageBackground: 22,

    /**
     * Use auto-selection based on Style
     */
    NSVisualEffectMaterialAuto: -1,
};

/**
 * Permission is the policy applied to a PermissionType. The values are kept in
 * step with the native WebView2 permission-state ABI (Default=0, Allow=1,
 * Deny=2) so the Windows backend needs no translation.
 * @readonly
 * @enum {number}
 */
export const Permission = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * PermissionDefault uses the platform's native handling and is the zero
     * value. On macOS (TCC) and Windows (WebView2) this presents the OS/webview
     * permission prompt to the user. Linux/WebKitGTK has no prompt mechanism,
     * so media capture (camera/microphone) is allowed — restoring getUserMedia
     * for app content — and other capabilities are denied.
     */
    PermissionDefault: 0,

    /**
     * PermissionAllow grants the capability without prompting.
     */
    PermissionAllow: 1,

    /**
     * PermissionDeny denies the capability without prompting.
     */
    PermissionDeny: 2,
};

/**
 * PermissionType identifies a capability that web content can request from
 * the webview (camera, microphone, …). It is the cross-platform equivalent of
 * the platform-specific permission-kind enums.
 * @readonly
 * @enum {number}
 */
export const PermissionType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    PermissionMicrophone: 0,
    PermissionCamera: 1,
    PermissionGeolocation: 2,
    PermissionNotifications: 3,
    PermissionClipboardRead: 4,
};

export class RGBA {
    /**
     * Creates a new RGBA instance.
     * @param {Partial<RGBA>} [$$source = {}] - The source object to create the RGBA.
     */
    constructor($$source = {}) {
        if (!("Red" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Red"] = 0;
        }
        if (!("Green" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Green"] = 0;
        }
        if (!("Blue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Blue"] = 0;
        }
        if (!("Alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Alpha"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RGBA instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RGBA}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RGBA(/** @type {Partial<RGBA>} */($$parsedSource));
    }
}

export class Rect {
    /**
     * Creates a new Rect instance.
     * @param {Partial<Rect>} [$$source = {}] - The source object to create the Rect.
     */
    constructor($$source = {}) {
        if (!("X" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Y"] = 0;
        }
        if (!("Width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rect instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rect}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rect(/** @type {Partial<Rect>} */($$parsedSource));
    }
}

export class Screen {
    /**
     * Creates a new Screen instance.
     * @param {Partial<Screen>} [$$source = {}] - The source object to create the Screen.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * A unique identifier for the display
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * The name of the display
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("ScaleFactor" in $$source)) {
            /**
             * The scale factor of the display (DPI/96)
             * @member
             * @type {number}
             */
            this["ScaleFactor"] = 0;
        }
        if (!("X" in $$source)) {
            /**
             * The x-coordinate of the top-left corner of the rectangle
             * @member
             * @type {number}
             */
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            /**
             * The y-coordinate of the top-left corner of the rectangle
             * @member
             * @type {number}
             */
            this["Y"] = 0;
        }
        if (!("Size" in $$source)) {
            /**
             * The size of the display
             * @member
             * @type {Size}
             */
            this["Size"] = (new Size());
        }
        if (!("Bounds" in $$source)) {
            /**
             * The bounds of the display
             * @member
             * @type {Rect}
             */
            this["Bounds"] = (new Rect());
        }
        if (!("PhysicalBounds" in $$source)) {
            /**
             * The physical bounds of the display (before scaling)
             * @member
             * @type {Rect}
             */
            this["PhysicalBounds"] = (new Rect());
        }
        if (!("WorkArea" in $$source)) {
            /**
             * The work area of the display
             * @member
             * @type {Rect}
             */
            this["WorkArea"] = (new Rect());
        }
        if (!("PhysicalWorkArea" in $$source)) {
            /**
             * The physical work area of the display (before scaling)
             * @member
             * @type {Rect}
             */
            this["PhysicalWorkArea"] = (new Rect());
        }
        if (!("IsPrimary" in $$source)) {
            /**
             * Whether this is the primary display
             * @member
             * @type {boolean}
             */
            this["IsPrimary"] = false;
        }
        if (!("Rotation" in $$source)) {
            /**
             * The rotation of the display
             * @member
             * @type {number}
             */
            this["Rotation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Screen instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Screen}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType42;
        const $$createField6_0 = $$createType43;
        const $$createField7_0 = $$createType43;
        const $$createField8_0 = $$createType43;
        const $$createField9_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Size" in $$parsedSource) {
            $$parsedSource["Size"] = $$createField5_0($$parsedSource["Size"]);
        }
        if ("Bounds" in $$parsedSource) {
            $$parsedSource["Bounds"] = $$createField6_0($$parsedSource["Bounds"]);
        }
        if ("PhysicalBounds" in $$parsedSource) {
            $$parsedSource["PhysicalBounds"] = $$createField7_0($$parsedSource["PhysicalBounds"]);
        }
        if ("WorkArea" in $$parsedSource) {
            $$parsedSource["WorkArea"] = $$createField8_0($$parsedSource["WorkArea"]);
        }
        if ("PhysicalWorkArea" in $$parsedSource) {
            $$parsedSource["PhysicalWorkArea"] = $$createField9_0($$parsedSource["PhysicalWorkArea"]);
        }
        return new Screen(/** @type {Partial<Screen>} */($$parsedSource));
    }
}

export class ScreenManager {
    /**
     * Creates a new ScreenManager instance.
     * @param {Partial<ScreenManager>} [$$source = {}] - The source object to create the ScreenManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenManager(/** @type {Partial<ScreenManager>} */($$parsedSource));
    }
}

export class Size {
    /**
     * Creates a new Size instance.
     * @param {Partial<Size>} [$$source = {}] - The source object to create the Size.
     */
    constructor($$source = {}) {
        if (!("Width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Size instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Size}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Size(/** @type {Partial<Size>} */($$parsedSource));
    }
}

/**
 * SystemTrayManager manages system tray-related operations
 */
export class SystemTrayManager {
    /**
     * Creates a new SystemTrayManager instance.
     * @param {Partial<SystemTrayManager>} [$$source = {}] - The source object to create the SystemTrayManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemTrayManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemTrayManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemTrayManager(/** @type {Partial<SystemTrayManager>} */($$parsedSource));
    }
}

export class TextTheme {
    /**
     * Creates a new TextTheme instance.
     * @param {Partial<TextTheme>} [$$source = {}] - The source object to create the TextTheme.
     */
    constructor($$source = {}) {
        if (!("Text" in $$source)) {
            /**
             * Text is the colour of the text
             * @member
             * @type {number | null}
             */
            this["Text"] = null;
        }
        if (!("Background" in $$source)) {
            /**
             * Background is the background colour of the text
             * @member
             * @type {number | null}
             */
            this["Background"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TextTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextTheme(/** @type {Partial<TextTheme>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const Theme = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * SystemDefault will use whatever the system theme is. The application will follow system theme changes.
     */
    SystemDefault: 0,

    /**
     * Dark Mode
     */
    Dark: 1,

    /**
     * Light Mode
     */
    Light: 2,
};

/**
 * ThemeSettings defines custom colours to use in dark or light mode.
 * They may be set using the hex values: 0x00BBGGRR
 */
export class ThemeSettings {
    /**
     * Creates a new ThemeSettings instance.
     * @param {Partial<ThemeSettings>} [$$source = {}] - The source object to create the ThemeSettings.
     */
    constructor($$source = {}) {
        if (!("DarkModeActive" in $$source)) {
            /**
             * Dark mode active window
             * @member
             * @type {WindowTheme | null}
             */
            this["DarkModeActive"] = null;
        }
        if (!("DarkModeInactive" in $$source)) {
            /**
             * Dark mode inactive window
             * @member
             * @type {WindowTheme | null}
             */
            this["DarkModeInactive"] = null;
        }
        if (!("LightModeActive" in $$source)) {
            /**
             * Light mode active window
             * @member
             * @type {WindowTheme | null}
             */
            this["LightModeActive"] = null;
        }
        if (!("LightModeInactive" in $$source)) {
            /**
             * Light mode inactive window
             * @member
             * @type {WindowTheme | null}
             */
            this["LightModeInactive"] = null;
        }
        if (!("DarkModeMenuBar" in $$source)) {
            /**
             * Dark mode MenuBar
             * @member
             * @type {MenuBarTheme | null}
             */
            this["DarkModeMenuBar"] = null;
        }
        if (!("LightModeMenuBar" in $$source)) {
            /**
             * Light mode MenuBar
             * @member
             * @type {MenuBarTheme | null}
             */
            this["LightModeMenuBar"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType45;
        const $$createField1_0 = $$createType45;
        const $$createField2_0 = $$createType45;
        const $$createField3_0 = $$createType45;
        const $$createField4_0 = $$createType47;
        const $$createField5_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DarkModeActive" in $$parsedSource) {
            $$parsedSource["DarkModeActive"] = $$createField0_0($$parsedSource["DarkModeActive"]);
        }
        if ("DarkModeInactive" in $$parsedSource) {
            $$parsedSource["DarkModeInactive"] = $$createField1_0($$parsedSource["DarkModeInactive"]);
        }
        if ("LightModeActive" in $$parsedSource) {
            $$parsedSource["LightModeActive"] = $$createField2_0($$parsedSource["LightModeActive"]);
        }
        if ("LightModeInactive" in $$parsedSource) {
            $$parsedSource["LightModeInactive"] = $$createField3_0($$parsedSource["LightModeInactive"]);
        }
        if ("DarkModeMenuBar" in $$parsedSource) {
            $$parsedSource["DarkModeMenuBar"] = $$createField4_0($$parsedSource["DarkModeMenuBar"]);
        }
        if ("LightModeMenuBar" in $$parsedSource) {
            $$parsedSource["LightModeMenuBar"] = $$createField5_0($$parsedSource["LightModeMenuBar"]);
        }
        return new ThemeSettings(/** @type {Partial<ThemeSettings>} */($$parsedSource));
    }
}

/**
 * WebviewGpuPolicy values used for determining the webview's hardware acceleration policy.
 * @readonly
 * @enum {number}
 */
export const WebviewGpuPolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * WebviewGpuPolicyAlways Hardware acceleration is always enabled.
     */
    WebviewGpuPolicyAlways: 0,

    /**
     * WebviewGpuPolicyOnDemand Hardware acceleration is enabled/disabled as request by web contents.
     */
    WebviewGpuPolicyOnDemand: 1,

    /**
     * WebviewGpuPolicyNever Hardware acceleration is always disabled.
     */
    WebviewGpuPolicyNever: 2,
};

export class WebviewWindowOptions {
    /**
     * Creates a new WebviewWindowOptions instance.
     * @param {Partial<WebviewWindowOptions>} [$$source = {}] - The source object to create the WebviewWindowOptions.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * Name is a unique identifier that can be given to a window.
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * Title is the title of the window.
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Width" in $$source)) {
            /**
             * Width is the starting width of the window.
             * @member
             * @type {number}
             */
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * Height is the starting height of the window.
             * @member
             * @type {number}
             */
            this["Height"] = 0;
        }
        if (!("AlwaysOnTop" in $$source)) {
            /**
             * AlwaysOnTop will make the window float above other windows.
             * @member
             * @type {boolean}
             */
            this["AlwaysOnTop"] = false;
        }
        if (!("URL" in $$source)) {
            /**
             * URL is the URL to load in the window.
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("DisableResize" in $$source)) {
            /**
             * DisableResize will disable the ability to resize the window.
             * @member
             * @type {boolean}
             */
            this["DisableResize"] = false;
        }
        if (!("Frameless" in $$source)) {
            /**
             * Frameless will remove the window frame.
             * @member
             * @type {boolean}
             */
            this["Frameless"] = false;
        }
        if (!("MinWidth" in $$source)) {
            /**
             * MinWidth is the minimum width of the window.
             * @member
             * @type {number}
             */
            this["MinWidth"] = 0;
        }
        if (!("MinHeight" in $$source)) {
            /**
             * MinHeight is the minimum height of the window.
             * @member
             * @type {number}
             */
            this["MinHeight"] = 0;
        }
        if (!("MaxWidth" in $$source)) {
            /**
             * MaxWidth is the maximum width of the window.
             * @member
             * @type {number}
             */
            this["MaxWidth"] = 0;
        }
        if (!("MaxHeight" in $$source)) {
            /**
             * MaxHeight is the maximum height of the window.
             * @member
             * @type {number}
             */
            this["MaxHeight"] = 0;
        }
        if (!("StartState" in $$source)) {
            /**
             * StartState indicates the state of the window when it is first shown.
             * Default: WindowStateNormal
             * @member
             * @type {WindowState}
             */
            this["StartState"] = WindowState.$zero;
        }
        if (!("BackgroundType" in $$source)) {
            /**
             * BackgroundType is the type of background to use for the window.
             * Default: BackgroundTypeSolid
             * @member
             * @type {BackgroundType}
             */
            this["BackgroundType"] = BackgroundType.$zero;
        }
        if (!("BackgroundColour" in $$source)) {
            /**
             * BackgroundColour is the colour to use for the window background.
             * @member
             * @type {RGBA}
             */
            this["BackgroundColour"] = (new RGBA());
        }
        if (!("HTML" in $$source)) {
            /**
             * HTML is the HTML to load in the window.
             * @member
             * @type {string}
             */
            this["HTML"] = "";
        }
        if (!("AllowSimpleEventEmit" in $$source)) {
            /**
             * AllowSimpleEventEmit gates the `wails:event:emit:<name>` postMessage
             * shortcut for this window. When true, JavaScript running in this
             * window can fire bare-named Wails custom events on the host bus via
             * `window._wails.invoke("wails:event:emit:<name>")`. The shortcut
             * exists so InitialHTML pages (loaded with no asset-server origin —
             * the framework's built-in updater window is the canonical case) can
             * still talk to the Go side without depending on the modern HTTP
             * runtime that requires `fetch("/wails/runtime")` to work.
             * 
             * SECURITY: leave this off (the default) unless you control every byte
             * of HTML that this window will ever load. When enabled, ANY script
             * running in the page — including content from a remote URL or any
             * XSS sink in user-supplied content — can synthesise Wails custom
             * events. The shortcut conveys bare names only (no payload) and
             * cannot reach the binding/Call path, but it CAN trigger any
             * `app.Event.On(name, ...)` handler your application code registers.
             * If you have a handler that performs a privileged action based on
             * the event name alone, that handler is exposed to anyone with
             * scripting access to this window.
             * 
             * Use [WebviewWindow.AsUpdaterWindow] in concert with
             * updater.BYOWindow to opt in cleanly when you're writing your own
             * updater UI; otherwise leave this false.
             * @member
             * @type {boolean}
             */
            this["AllowSimpleEventEmit"] = false;
        }
        if (!("JS" in $$source)) {
            /**
             * JS is the JavaScript to load in the window.
             * @member
             * @type {string}
             */
            this["JS"] = "";
        }
        if (!("CSS" in $$source)) {
            /**
             * CSS is the CSS to load in the window.
             * @member
             * @type {string}
             */
            this["CSS"] = "";
        }
        if (!("InitialPosition" in $$source)) {
            /**
             * Initial Position
             * @member
             * @type {WindowStartPosition}
             */
            this["InitialPosition"] = WindowStartPosition.$zero;
        }
        if (!("X" in $$source)) {
            /**
             * X is the starting X position of the window.
             * @member
             * @type {number}
             */
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            /**
             * Y is the starting Y position of the window.
             * @member
             * @type {number}
             */
            this["Y"] = 0;
        }
        if (!("Screen" in $$source)) {
            /**
             * Screen specifies the target screen for initial window placement.
             * When set with WindowCentered, the window is centered on that screen's WorkArea.
             * When set with WindowXY, X/Y are treated as relative to that screen's WorkArea origin.
             * When nil, OS default behavior is used.
             * @member
             * @type {Screen | null}
             */
            this["Screen"] = null;
        }
        if (!("Hidden" in $$source)) {
            /**
             * Hidden will hide the window when it is first created.
             * @member
             * @type {boolean}
             */
            this["Hidden"] = false;
        }
        if (!("Zoom" in $$source)) {
            /**
             * Zoom is the zoom level of the window.
             * @member
             * @type {number}
             */
            this["Zoom"] = 0;
        }
        if (!("ZoomControlEnabled" in $$source)) {
            /**
             * ZoomControlEnabled will enable the zoom control.
             * @member
             * @type {boolean}
             */
            this["ZoomControlEnabled"] = false;
        }
        if (!("EnableFileDrop" in $$source)) {
            /**
             * EnableFileDrop enables drag and drop of files onto the window.
             * When enabled, files dragged from the OS onto elements with the
             * `data-file-drop-target` attribute will trigger a FilesDropped event.
             * @member
             * @type {boolean}
             */
            this["EnableFileDrop"] = false;
        }
        if (!("Permissions" in $$source)) {
            /**
             * Permissions controls how capability requests (camera, microphone, …)
             * from the web content are handled, per PermissionType. Unset entries use
             * PermissionDefault. Cross-platform; see the Permission constants for the
             * per-platform meaning of the default.
             * @member
             * @type {{ [_ in PermissionType]?: Permission }}
             */
            this["Permissions"] = {};
        }
        if (!("OpenInspectorOnStartup" in $$source)) {
            /**
             * OpenInspectorOnStartup will open the inspector when the window is first shown.
             * @member
             * @type {boolean}
             */
            this["OpenInspectorOnStartup"] = false;
        }
        if (!("Mac" in $$source)) {
            /**
             * Mac options
             * @member
             * @type {MacWindow}
             */
            this["Mac"] = (new MacWindow());
        }
        if (!("Windows" in $$source)) {
            /**
             * Windows options
             * @member
             * @type {WindowsWindow}
             */
            this["Windows"] = (new WindowsWindow());
        }
        if (!("Linux" in $$source)) {
            /**
             * Linux options
             * @member
             * @type {LinuxWindow}
             */
            this["Linux"] = (new LinuxWindow());
        }
        if (!("MinimiseButtonState" in $$source)) {
            /**
             * Toolbar button states
             * @member
             * @type {ButtonState}
             */
            this["MinimiseButtonState"] = ButtonState.$zero;
        }
        if (!("MaximiseButtonState" in $$source)) {
            /**
             * @member
             * @type {ButtonState}
             */
            this["MaximiseButtonState"] = ButtonState.$zero;
        }
        if (!("CloseButtonState" in $$source)) {
            /**
             * @member
             * @type {ButtonState}
             */
            this["CloseButtonState"] = ButtonState.$zero;
        }
        if (!("FullscreenButtonState" in $$source)) {
            /**
             * FullscreenButtonState controls the fullscreen button state.
             * On macOS this targets NSWindowZoomButton (the same green button as MaximiseButtonState);
             * the more restrictive of the two states is applied. On other platforms this is a no-op.
             * @member
             * @type {ButtonState}
             */
            this["FullscreenButtonState"] = ButtonState.$zero;
        }
        if (!("DevToolsEnabled" in $$source)) {
            /**
             * If true, the window's devtools will be available (default true in builds without the `production` build tag)
             * @member
             * @type {boolean}
             */
            this["DevToolsEnabled"] = false;
        }
        if (!("DefaultContextMenuDisabled" in $$source)) {
            /**
             * If true, the window's default context menu will be disabled (default false)
             * @member
             * @type {boolean}
             */
            this["DefaultContextMenuDisabled"] = false;
        }
        if (!("KeyBindings" in $$source)) {
            /**
             * KeyBindings is a map of key bindings to functions
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["KeyBindings"] = {};
        }
        if (!("IgnoreMouseEvents" in $$source)) {
            /**
             * IgnoreMouseEvents will ignore mouse events in the window (Windows + Mac only)
             * @member
             * @type {boolean}
             */
            this["IgnoreMouseEvents"] = false;
        }
        if (!("ContentProtectionEnabled" in $$source)) {
            /**
             * ContentProtectionEnabled specifies whether content protection is enabled, preventing screen capture and recording.
             * Effective on Windows and macOS only; no-op on Linux.
             * Best-effort protection with platform-specific caveats (see docs).
             * @member
             * @type {boolean}
             */
            this["ContentProtectionEnabled"] = false;
        }
        if (!("HideOnFocusLost" in $$source)) {
            /**
             * HideOnFocusLost will hide the window when it loses focus.
             * Useful for popup/transient windows like systray attached windows.
             * On Linux with focus-follows-mouse WMs (Hyprland, Sway, i3), this is automatically disabled
             * as it would cause the window to hide immediately when the mouse moves away.
             * @member
             * @type {boolean}
             */
            this["HideOnFocusLost"] = false;
        }
        if (!("HideOnEscape" in $$source)) {
            /**
             * HideOnEscape will hide the window when the Escape key is pressed.
             * Useful for popup/transient windows that should dismiss on Escape.
             * @member
             * @type {boolean}
             */
            this["HideOnEscape"] = false;
        }
        if (!("UseApplicationMenu" in $$source)) {
            /**
             * UseApplicationMenu indicates this window should use the application menu
             * set via app.Menu.Set() instead of requiring a window-specific menu.
             * On macOS this has no effect as the application menu is always global.
             * On Windows/Linux, if true and no explicit window menu is set, the window
             * will use the application menu. Defaults to false for backwards compatibility.
             * @member
             * @type {boolean}
             */
            this["UseApplicationMenu"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebviewWindowOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebviewWindowOptions}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType32;
        const $$createField22_0 = $$createType49;
        const $$createField27_0 = $$createType50;
        const $$createField29_0 = $$createType51;
        const $$createField30_0 = $$createType52;
        const $$createField31_0 = $$createType53;
        const $$createField38_0 = $$createType54;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BackgroundColour" in $$parsedSource) {
            $$parsedSource["BackgroundColour"] = $$createField14_0($$parsedSource["BackgroundColour"]);
        }
        if ("Screen" in $$parsedSource) {
            $$parsedSource["Screen"] = $$createField22_0($$parsedSource["Screen"]);
        }
        if ("Permissions" in $$parsedSource) {
            $$parsedSource["Permissions"] = $$createField27_0($$parsedSource["Permissions"]);
        }
        if ("Mac" in $$parsedSource) {
            $$parsedSource["Mac"] = $$createField29_0($$parsedSource["Mac"]);
        }
        if ("Windows" in $$parsedSource) {
            $$parsedSource["Windows"] = $$createField30_0($$parsedSource["Windows"]);
        }
        if ("Linux" in $$parsedSource) {
            $$parsedSource["Linux"] = $$createField31_0($$parsedSource["Linux"]);
        }
        if ("KeyBindings" in $$parsedSource) {
            $$parsedSource["KeyBindings"] = $$createField38_0($$parsedSource["KeyBindings"]);
        }
        return new WebviewWindowOptions(/** @type {Partial<WebviewWindowOptions>} */($$parsedSource));
    }
}

/**
 * @typedef {any} Window
 */

/**
 * WindowManager manages all window-related operations
 */
export class WindowManager {
    /**
     * Creates a new WindowManager instance.
     * @param {Partial<WindowManager>} [$$source = {}] - The source object to create the WindowManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowManager(/** @type {Partial<WindowManager>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const WindowStartPosition = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    WindowCentered: 0,
    WindowXY: 1,
};

/**
 * @readonly
 * @enum {number}
 */
export const WindowState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    WindowStateNormal: 0,
    WindowStateMinimised: 1,
    WindowStateMaximised: 2,
    WindowStateFullscreen: 3,
};

export class WindowTheme {
    /**
     * Creates a new WindowTheme instance.
     * @param {Partial<WindowTheme>} [$$source = {}] - The source object to create the WindowTheme.
     */
    constructor($$source = {}) {
        if (!("BorderColour" in $$source)) {
            /**
             * BorderColour is the colour of the window border
             * @member
             * @type {number | null}
             */
            this["BorderColour"] = null;
        }
        if (!("TitleBarColour" in $$source)) {
            /**
             * TitleBarColour is the colour of the window title bar
             * @member
             * @type {number | null}
             */
            this["TitleBarColour"] = null;
        }
        if (!("TitleTextColour" in $$source)) {
            /**
             * TitleTextColour is the colour of the window title text
             * @member
             * @type {number | null}
             */
            this["TitleTextColour"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowTheme(/** @type {Partial<WindowTheme>} */($$parsedSource));
    }
}

export class WindowsWindow {
    /**
     * Creates a new WindowsWindow instance.
     * @param {Partial<WindowsWindow>} [$$source = {}] - The source object to create the WindowsWindow.
     */
    constructor($$source = {}) {
        if (!("BackdropType" in $$source)) {
            /**
             * Select the type of translucent backdrop. Requires Windows 11 22621 or later.
             * Only used when window's `BackgroundType` is set to `BackgroundTypeTranslucent`.
             * Default: Auto
             * @member
             * @type {BackdropType}
             */
            this["BackdropType"] = BackdropType.$zero;
        }
        if (!("DisableIcon" in $$source)) {
            /**
             * Disable the icon in the titlebar
             * Default: false
             * @member
             * @type {boolean}
             */
            this["DisableIcon"] = false;
        }
        if (!("Theme" in $$source)) {
            /**
             * Theme (Dark / Light / SystemDefault)
             * Default: SystemDefault - The application will follow system theme changes.
             * @member
             * @type {Theme}
             */
            this["Theme"] = Theme.$zero;
        }
        if (!("CustomTheme" in $$source)) {
            /**
             * Specify custom colours to use for dark/light mode
             * Default: nil
             * @member
             * @type {ThemeSettings}
             */
            this["CustomTheme"] = (new ThemeSettings());
        }
        if (!("DisableFramelessWindowDecorations" in $$source)) {
            /**
             * Disable all window decorations in Frameless mode, which means no "Aero Shadow" and no "Rounded Corner" will be shown.
             * "Rounded Corners" are only available on Windows 11.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["DisableFramelessWindowDecorations"] = false;
        }
        if (!("WindowMask" in $$source)) {
            /**
             * WindowMask is used to set the window shape. Use a PNG with an alpha channel to create a custom shape.
             * Default: nil
             * @member
             * @type {string}
             */
            this["WindowMask"] = "";
        }
        if (!("WindowMaskDraggable" in $$source)) {
            /**
             * WindowMaskDraggable is used to make the window draggable by clicking on the window mask.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["WindowMaskDraggable"] = false;
        }
        if (!("WindowDidMoveDebounceMS" in $$source)) {
            /**
             * WindowDidMoveDebounceMS is the amount of time to debounce the WindowDidMove event
             * when moving the window
             * Default: 0
             * @member
             * @type {number}
             */
            this["WindowDidMoveDebounceMS"] = 0;
        }
        if (!("EventMapping" in $$source)) {
            /**
             * Event mapping for the window. This allows you to define a translation from one event to another.
             * Default: nil
             * @member
             * @type {{ [_ in events$0.WindowEventType]?: events$0.WindowEventType }}
             */
            this["EventMapping"] = {};
        }
        if (!("HiddenOnTaskbar" in $$source)) {
            /**
             * HiddenOnTaskbar hides the window from the taskbar
             * Default: false
             * @member
             * @type {boolean}
             */
            this["HiddenOnTaskbar"] = false;
        }
        if (!("EnableSwipeGestures" in $$source)) {
            /**
             * EnableSwipeGestures enables swipe gestures for the window
             * Default: false
             * @member
             * @type {boolean}
             */
            this["EnableSwipeGestures"] = false;
        }
        if (!("Menu" in $$source)) {
            /**
             * Menu is the menu to use for the window.
             * @member
             * @type {Menu | null}
             */
            this["Menu"] = null;
        }
        if (!("DisableMenu" in $$source)) {
            /**
             * DisableMenu will disable the menu for the window.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["DisableMenu"] = false;
        }
        if (!("Permissions" in $$source)) {
            /**
             * Permissions map for WebView2. If empty, default permissions will be granted.
             * @member
             * @type {{ [_ in CoreWebView2PermissionKind]?: CoreWebView2PermissionState }}
             */
            this["Permissions"] = {};
        }
        if (!("ExStyle" in $$source)) {
            /**
             * ExStyle is the extended window style
             * @member
             * @type {number}
             */
            this["ExStyle"] = 0;
        }
        if (!("GeneralAutofillEnabled" in $$source)) {
            /**
             * GeneralAutofillEnabled enables general autofill
             * @member
             * @type {boolean}
             */
            this["GeneralAutofillEnabled"] = false;
        }
        if (!("PasswordAutosaveEnabled" in $$source)) {
            /**
             * PasswordAutosaveEnabled enables autosaving passwords
             * @member
             * @type {boolean}
             */
            this["PasswordAutosaveEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowsWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowsWindow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType55;
        const $$createField5_0 = $Create.ByteSlice;
        const $$createField8_0 = $$createType37;
        const $$createField11_0 = $$createType31;
        const $$createField13_0 = $$createType56;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CustomTheme" in $$parsedSource) {
            $$parsedSource["CustomTheme"] = $$createField3_0($$parsedSource["CustomTheme"]);
        }
        if ("WindowMask" in $$parsedSource) {
            $$parsedSource["WindowMask"] = $$createField5_0($$parsedSource["WindowMask"]);
        }
        if ("EventMapping" in $$parsedSource) {
            $$parsedSource["EventMapping"] = $$createField8_0($$parsedSource["EventMapping"]);
        }
        if ("Menu" in $$parsedSource) {
            $$parsedSource["Menu"] = $$createField11_0($$parsedSource["Menu"]);
        }
        if ("Permissions" in $$parsedSource) {
            $$parsedSource["Permissions"] = $$createField13_0($$parsedSource["Permissions"]);
        }
        return new WindowsWindow(/** @type {Partial<WindowsWindow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WindowManager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ContextMenuManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = KeyBindingManager.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = BrowserManager.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = EnvironmentManager.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = DialogManager.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = EventManager.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = MenuManager.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = ScreenManager.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = ClipboardManager.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = SystemTrayManager.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = AutostartManager.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = GlobalShortcutManager.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = updater$0.Updater.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = slog$0.Logger.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = Menu.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = RGBA.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = optional$0.Var.createFrom($Create.Any);
const $$createType35 = optional$0.Var.createFrom($Create.Any);
const $$createType36 = MacTitleBar.createFrom;
const $$createType37 = $Create.Map($Create.Any, $Create.Any);
const $$createType38 = MacWebviewPreferences.createFrom;
const $$createType39 = MacLiquidGlass.createFrom;
const $$createType40 = TextTheme.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = Size.createFrom;
const $$createType43 = Rect.createFrom;
const $$createType44 = WindowTheme.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = MenuBarTheme.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = Screen.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = $Create.Map($Create.Any, $Create.Any);
const $$createType51 = MacWindow.createFrom;
const $$createType52 = WindowsWindow.createFrom;
const $$createType53 = LinuxWindow.createFrom;
const $$createType54 = $Create.Map($Create.Any, $Create.Any);
const $$createType55 = ThemeSettings.createFrom;
const $$createType56 = $Create.Map($Create.Any, $Create.Any);
