// Code generated by build/scripts/gen-brand.mjs. DO NOT EDIT.

export const company = "Quad4";
export const displayName = "Ren Browser";
export const slug = "renbrowser";
export const bundleId = "io.quad4.renbrowser";
export const description = "Reticulum browser for NomadNet pages";
export const tagline = "Reticulum browser for NomadNet pages.";
export const comments = "Micron-first mesh browser for NomadNet";
export const copyright = "(c) 2026 Quad4";
export const version = "0.2.0";
export const homepage = "https://quad4.io";
export const dataDir = ".renbrowser";
export const dbFile = "renbrowser.db";
export const envPrefix = "REN_BROWSER";
export const localStoragePrefix = "renbrowser";
export const indexedDbName = "renbrowser_micron_wasm_parsers";
export const proxyHeader = "X-RenBrowser-Base-Path";
export const tempFilePrefix = "renbrowser-rns-";
export const wailsVersion = "v3.0.0-alpha2";
export const wasmExecDomId = "renbrowser-micron-wasm-exec";
export const wasmGlobalFlag = "__renbrowserMicronWasmWrapped";

export function localStorageKey(safe: string, dataVersion: number): string {
  return `${localStoragePrefix}:${safe}:v${dataVersion}`;
}

export function exportFilename(kind: "devlogs" | "theme"): string {
  return `${slug}-${kind}.json`;
}
