// SPDX-License-Identifier: MIT
export {
  company,
  displayName,
  slug,
  bundleId,
  description,
  tagline,
  comments,
  copyright,
  version,
  homepage,
  dataDir,
  dbFile,
  envPrefix,
  localStoragePrefix,
  indexedDbName,
  proxyHeader,
  tempFilePrefix,
  wailsVersion,
  wasmExecDomId,
  wasmGlobalFlag,
  localStorageKey,
  exportFilename,
} from "./brand.gen.js";
